### ISSUE TITLE
Segfault when running

### ISSUE THREAD

**Issue by felixonmars** [ariya/phantomjs#10782]
_**[felixonm...@gmail.com](http://code.google.com/u/110500710996969120327/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
1.6.1
> 
> <b>What steps will reproduce the problem?</b>
$ phantomjs
> 
> <b>What is the expected output? What do you see instead?</b>
Some help msg, but I see segfault.
> 
> <b>Which operating system are you using?</b>
Archlinux x64
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
Compiled from source.
> 
> <b>Please provide any additional information below.</b>

> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff71e1b49 in ?? () from /usr/lib/libQtWebKit.so.4
> (gdb) where
> #0  0x00007ffff71e1b49 in ?? () from /usr/lib/libQtWebKit.so.4
> #1  0x00007ffff69711e3 in WebCore::FrameLoaderClientQt::userAgent(WebCore::KURL 
> const&amp;) () from /usr/lib/libQtWebKit.so.4
> #2  0x00007ffff6cb2fd9 in ?? () from /usr/lib/libQtWebKit.so.4
> #3  0x00007ffff6cb3082 in ?? () from /usr/lib/libQtWebKit.so.4
> #4  0x00007ffff6cdebb3 in ?? () from /usr/lib/libQtWebKit.so.4
> #5  0x00007ffff6cdb66d in ?? () from /usr/lib/libQtWebKit.so.4
> #6  0x00007ffff6cc6d29 in ?? () from /usr/lib/libQtWebKit.so.4
> #7  0x00007ffff6cc82d6 in ?? () from /usr/lib/libQtWebKit.so.4
> #8  0x00007ffff6cc9d36 in ?? () from /usr/lib/libQtWebKit.so.4
> #9  0x00007ffff6ca52f5 in ?? () from /usr/lib/libQtWebKit.so.4
> #10 0x00007ffff6cae947 in ?? () from /usr/lib/libQtWebKit.so.4
> #11 0x00007ffff6cb8780 in ?? () from /usr/lib/libQtWebKit.so.4
> #12 0x00007ffff6cb87ce in ?? () from /usr/lib/libQtWebKit.so.4
> #13 0x00007ffff6ccd98d in ?? () from /usr/lib/libQtWebKit.so.4
> #14 0x00007ffff6cd2109 in ?? () from /usr/lib/libQtWebKit.so.4
> #15 0x00007ffff6979767 in WebCore::FrameLoaderClientQt::dispatchDecidePolicyForN
> avigationAction(void (WebCore::PolicyChecker::*)(WebCore::PolicyAction), WebCore
> ::NavigationAction const&amp;, WebCore::ResourceRequest const&amp;, WTF::PassRefPtr&lt;WebC
> ore::FormState&gt;) () from /usr/lib/libQtWebKit.so.4
> #16 0x00007ffff6cd325a in ?? () from /usr/lib/libQtWebKit.so.4
> #17 0x00007ffff6cb8b59 in ?? () from /usr/lib/libQtWebKit.so.4
> #18 0x00007ffff6cb8d10 in ?? () from /usr/lib/libQtWebKit.so.4
> #19 0x00007ffff6cb8e6b in ?? () from /usr/lib/libQtWebKit.so.4
> #20 0x00007ffff69392a8 in QWebFrame::setHtml(QString const&amp;, QUrl const&amp;) () fro
> m /usr/lib/libQtWebKit.so.4
> #21 0x000000000041597a in ?? ()
> #22 0x000000000040f84e in ?? ()
> #23 0x000000000040dd87 in ?? ()
> #24 0x00007ffff3b92725 in __libc_start_main () from /usr/lib/libc.so.6
> #25 0x000000000040dff1 in ?? ()

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #782](http://code.google.com/p/phantomjs/issues/detail?id=782).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by felixonmars** [comment]
Closing as it's not reproducible now.
