### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10781]
_**[miguel.a...@neoscopio.com](http://code.google.com/u/104807852519757840256/) commented:**_
> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>

> <b>What steps will reproduce the problem?</b>
1. $session-&gt;open('http://www.uzo.pt/pt/meu-uzo/pagina.uzo') 
> <b>2.</b>
<b>3.</b>

> <b>What is the expected output? What do you see instead?</b>

> <b>Which operating system are you using?</b>
Linux
> <b>Did you use binary PhantomJS or did you compile it from source?</b>

> Compiled from source, dev branch
> 
> <b>Please provide any additional information below.</b>

> $ gdb ./phantomjs/bin/phantomjs
> GNU gdb (Ubuntu/Linaro 7.4-2012.04-0ubuntu2) 7.4-2012.04
> Copyright (C) 2012 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later &lt;http://gnu.org/licenses/gpl.html&gt;
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type &quot;show copying&quot;
> and &quot;show warranty&quot; for details.
> This GDB was configured as &quot;x86_64-linux-gnu&quot;.
> For bug reporting instructions, please see:
> &lt;http://bugs.launchpad.net/gdb-linaro/&gt;...
> Reading symbols from /home/alienation/projects/selenium/phantomjs/bin/phantomjs...(no debugging symbols found)...done.
> (gdb) run /home/alienation/projects/selenium/ghostdriver/src/main.js
> Starting program: /home/alienation/projects/selenium/phantomjs/bin/phantomjs /home/alienation/projects/selenium/ghostdriver/src/main.js
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library &quot;/lib/x86_64-linux-gnu/libthread_db.so.1&quot;.
> Creating CookieJar, but no file to store cookies was provided (use '--cookies-file=&lt;filename&gt;') 
> [New Thread 0x7ffff6005700 (LWP 6234)]
> [New Thread 0x7ffff57fc700 (LWP 6235)]
> [New Thread 0x7fffaffb9700 (LWP 6236)]
> [New Thread 0x7fffaf7b8700 (LWP 6237)]
> [New Thread 0x7fffaefb7700 (LWP 6238)]
> [New Thread 0x7fffae7b6700 (LWP 6239)]
> [New Thread 0x7fffa7fff700 (LWP 6240)]
> [New Thread 0x7fffadfb5700 (LWP 6241)]
> [New Thread 0x7fffad7b4700 (LWP 6242)]
> [New Thread 0x7fffacfb3700 (LWP 6243)]
> [New Thread 0x7fffa77fe700 (LWP 6244)]
> [New Thread 0x7fffa6ffd700 (LWP 6245)]
> [New Thread 0x7fffa67fc700 (LWP 6246)]
> Ghost Driver running on port 8080
> [New Thread 0x7fffa5ffb700 (LWP 6251)]
> [New Thread 0x7fffa57fa700 (LWP 6252)]
> [New Thread 0x7fff7bfff700 (LWP 6253)]
> [New Thread 0x7fff7b7fe700 (LWP 6254)]
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x00007fffb004f93e in ?? ()
> (gdb) bt
> #0  0x00007fffb004f93e in ?? ()
> #1  0x0000000000000000 in ?? ()
> (gdb)

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #781](http://code.google.com/p/phantomjs/issues/detail?id=781).
:star2: &nbsp; **2** people had starred this issue at the time of migration.

**Comment by Vitallium** [comment]
Closing due to inactivity and new released version.
