### ISSUE TITLE
Endless frame processing

### ISSUE THREAD

**Issue by maybeshewill** [ariya/phantomjs#11459]
Example command:

> ./phantomjs --debug=yes ../examples/rasterize.js http://anal.xxxselect.com/ test.png      

GDB:

```
2013-07-04T13:08:15 [DEBUG] Phantom - execute: Configuration 
2013-07-04T13:08:15 [DEBUG]      0 objectName : "" 
2013-07-04T13:08:15 [DEBUG]      1 cookiesFile : "" 
2013-07-04T13:08:15 [DEBUG]      2 diskCacheEnabled : "false" 
2013-07-04T13:08:15 [DEBUG]      3 maxDiskCacheSize : "-1" 
2013-07-04T13:08:15 [DEBUG]      4 ignoreSslErrors : "false" 
2013-07-04T13:08:15 [DEBUG]      5 localToRemoteUrlAccessEnabled : "false" 
2013-07-04T13:08:15 [DEBUG]      6 outputEncoding : "UTF-8" 
2013-07-04T13:08:15 [DEBUG]      7 proxyType : "http" 
2013-07-04T13:08:15 [DEBUG]      8 proxy : ":8" 
2013-07-04T13:08:15 [DEBUG]      9 proxyAuth : ":" 
2013-07-04T13:08:15 [DEBUG]      10 scriptEncoding : "UTF-8" 
2013-07-04T13:08:15 [DEBUG]      11 webSecurityEnabled : "true" 
2013-07-04T13:08:15 [DEBUG]      12 offlineStoragePath : "" 
2013-07-04T13:08:15 [DEBUG]      13 offlineStorageDefaultQuota : "-1" 
2013-07-04T13:08:15 [DEBUG]      14 printDebugMessages : "true" 
2013-07-04T13:08:15 [DEBUG]      15 javascriptCanOpenWindows : "true" 
2013-07-04T13:08:15 [DEBUG]      16 javascriptCanCloseWindows : "true" 
2013-07-04T13:08:15 [DEBUG]      17 sslProtocol : "sslv3" 
2013-07-04T13:08:15 [DEBUG]      18 sslCertificatesPath : "" 
2013-07-04T13:08:15 [DEBUG]      19 webdriver : ":" 
2013-07-04T13:08:15 [DEBUG]      20 webdriverLogFile : "" 
2013-07-04T13:08:15 [DEBUG]      21 webdriverLogLevel : "INFO" 
2013-07-04T13:08:15 [DEBUG]      22 webdriverSeleniumGridHub : "" 
2013-07-04T13:08:15 [DEBUG] Phantom - execute: Script & Arguments 
2013-07-04T13:08:15 [DEBUG]      script: "../examples/rasterize.js" 
2013-07-04T13:08:15 [DEBUG]      0 arg: "http://anal.xxxselect.com/" 
2013-07-04T13:08:15 [DEBUG]      1 arg: "test.png" 
2013-07-04T13:08:15 [DEBUG] Phantom - execute: Starting normal mode 
2013-07-04T13:08:15 [DEBUG] WebPage - setupFrame "" 
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/_coffee-script.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/package.json" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/coffee-script.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./lexer.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/././rewriter.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/././helpers.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./parser.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./helpers.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./nodes.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/././scope.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./././helpers.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/././lexer.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./././rewriter.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r") ) )  
2013-07-04T13:08:15 [DEBUG] WebPage - updateLoadingProgress: 10 
[New Thread 0x7fffaf3a9700 (LWP 10115)]
2013-07-04T13:08:15 [DEBUG] WebPage - updateLoadingProgress: 15 
2013-07-04T13:08:15 [DEBUG] WebPage - setupFrame "" 
2013-07-04T13:08:15 [DEBUG] WebPage - updateLoadingProgress: 20 
2013-07-04T13:08:15 [DEBUG] WebPage - updateLoadingProgress: 22 
2013-07-04T13:08:15 [DEBUG] WebPage - updateLoadingProgress: 23 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 23 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 25 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 30 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 32 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 34 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 37 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 39 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 42 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 44 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 46 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 49 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 53 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 57 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 60 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 63 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 67 
2013-07-04T13:08:16 [DEBUG] WebPage - updateLoadingProgress: 69 
2013-07-04T13:08:17 [DEBUG] WebPage - updateLoadingProgress: 70 
2013-07-04T13:08:17 [DEBUG] WebPage - updateLoadingProgress: 72 
2013-07-04T13:08:17 [DEBUG] WebPage - updateLoadingProgress: 74 
2013-07-04T13:08:17 [DEBUG] WebPage - updateLoadingProgress: 77 
2013-07-04T13:08:17 [DEBUG] WebPage - updateLoadingProgress: 80 
2013-07-04T13:08:17 [DEBUG] WebPage - updateLoadingProgress: 81 
2013-07-04T13:08:17 [DEBUG] WebPage - updateLoadingProgress: 100 
2013-07-04T13:08:17 [DEBUG] WebPage - setupFrame "" 
```

GDB BackTrace:

```
(gdb) bt
#0  0x00007ffff67fb033 in select () at ../sysdeps/unix/syscall-template.S:82
#1  0x0000000001c4480f in qt_safe_select(int, fd_set*, fd_set*, fd_set*, timeval const*) ()
#2  0x0000000001c466b7 in QEventDispatcherUNIXPrivate::doSelect(QFlags<QEventLoop::ProcessEventsFlag>, timeval*) ()
#3  0x0000000001c46af3 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#4  0x00000000015d52ca in QEventDispatcherQPA::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#5  0x0000000001c1cf62 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#6  0x0000000001c1d1bf in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#7  0x00000000018516fa in QDialog::exec() ()
#8  0x000000000186bb86 in QMessageBoxPrivate::showOldMessageBox(QWidget*, QMessageBox::Icon, QString const&, QString const&, int, int, int) ()
#9  0x000000000186bdc1 in showNewMessageBox(QWidget*, QMessageBox::Icon, QString const&, QString const&, QFlags<QMessageBox::StandardButton>, QMessageBox::StandardButton) [clone .constprop.28] ()
#10 0x000000000186be4f in QMessageBox::information(QWidget*, QString const&, QString const&, QFlags<QMessageBox::StandardButton>, QMessageBox::StandardButton) ()
#11 0x000000000048df4a in QWebPage::javaScriptConfirm(QWebFrame*, QString const&) ()
#12 0x00000000004ad85f in WebCore::ChromeClientQt::runJavaScriptConfirm(WebCore::Frame*, WTF::String const&) ()
#13 0x000000000083c534 in WebCore::Chrome::runJavaScriptConfirm(WebCore::Frame*, WTF::String const&) ()
#14 0x0000000000be8105 in WebCore::jsDOMWindowPrototypeFunctionConfirm(JSC::ExecState*) ()
#15 0x00007fffb00001e8 in ?? ()
#16 0x00007ffff4074160 in ?? ()
#17 0x00007fffb00583c5 in ?? ()
#18 0x00007fffb0057d28 in ?? ()
#19 0x00007fffafc3cd10 in ?? ()
#20 0x00007ffff7e3d550 in ?? ()
#21 0x00007fffafc93c10 in ?? ()
#22 0x0000000000000000 in ?? ()
```

This bug is 100% is not connected with InterruptJavaScript callback. I'll try to investigate further on my side

**Comment by majamusan** [comment]
yup same problem but a year later... must of been fixed
