### ISSUE TITLE
2.0.0 (development version) seems to have problems with fonts

### ISSUE THREAD

**Issue by kovzol** [ariya/phantomjs#12176]
PhantomJS crashes in some cases when I want to use fonts on a canvas, either WOFF or TTF. I couldn't narrow down the problem yet but it seems if I remove the fonts from the canvas there is no problem any longer. GDB backtrace:
```
#0  0x0000000000000000 in ?? ()
#1  0x0000000001ba02de in hb_getSFntTable(void*, unsigned int, unsigned char*, unsigned int*) ()
#2  0x0000000001e68c3d in getTableStream(void*, HB_Error (*)(void*, unsigned int, unsigned char*, unsigned int*), unsigned int) ()
#3  0x0000000001e6a710 in HB_LoadFace ()
#4  0x0000000001ba2b84 in QFontEngine::harfbuzzFont() const ()
#5  0x0000000001bb80ec in QTextEngine::shapeTextWithHarfbuzz(QScriptItem const&, unsigned short const*, int, QFontEngine*, QVector<unsigned int> const&, bool) const ()
#6  0x0000000001bbb81f in QTextEngine::shapeText(int) const ()
#7  0x0000000001bbc133 in QTextEngine::shape(int) const ()
#8  0x0000000001bcd57d in QTextLine::layout_helper(int) ()
#9  0x0000000001bce6cd in QTextLine::setLineWidth(double) ()
#10 0x0000000000752665 in WebCore::setupLayout(QTextLayout*, WebCore::TextRun const&) [clone .constprop.49] ()
#11 0x000000000075462e in WebCore::Font::drawComplexText(WebCore::GraphicsContext*, WebCore::TextRun const&, WebCore::FloatPoint const&, int, int) const ()
#12 0x0000000000746a7a in WebCore::GraphicsContext::drawBidiText(WebCore::Font const&, WebCore::TextRun const&, WebCore::FloatPoint const&, WebCore::Font::CustomFontNotReadyAction) ()
#13 0x00000000005c69ac in WebCore::CanvasRenderingContext2D::drawTextInternal(WTF::String const&, float, float, bool, float, bool) ()
#14 0x0000000000aae400 in WebCore::jsCanvasRenderingContext2DPrototypeFunctionFillText(JSC::ExecState*) ()
#15 0x00007fffb34790e5 in ?? ()
#16 0xffff000000000002 in ?? ()
#17 0x00000000015923aa in llint_op_call ()
#18 0x00000000ffffd7a0 in ?? ()
#19 0xffff00000000000a in ?? ()
#20 0xffff000080000000 in ?? ()
#21 0x00007fff00000003 in ?? ()
#22 0x00007fffb3a4f03a in ?? ()
#23 0x00007fff9a1c4298 in ?? ()
#24 0x00007fffa32d4980 in ?? ()
#25 0x00007fffffffd870 in ?? ()
#26 0x00007ffff7f2b000 in ?? ()
#27 0x00007fffb3479280 in ?? ()
#28 0x00007ffff7ed4610 in ?? ()
#29 0x00007fffb205ba80 in ?? ()
#30 0x0000000000000000 in ?? ()
```
My configure summary:
```
Build type:    linux-g++ (x86_64, CPU features: mmx sse sse2)
Platform notes:

            - Also available for Linux: linux-kcc linux-icc linux-cxx
        
qmake vars .......... QMAKE_CFLAGS = -g QMAKE_CXXFLAGS = -g styles += mac fusion windows DEFINES += QT_NO_MTDEV QMAKE_CFLAGS_FONTCONFIG =  QMAKE_LIBS_FONTCONFIG = -lfreetype -lfontconfig DEFINES += QT_NO_LIBUDEV DEFINES += QT_NO_EVDEV DEFINES += QT_NO_XCB DEFINES += QT_NO_XKBCOMMON DEFINES +=  "QT_NO_GRAPHICSVIEW" "QT_NO_GRAPHICSEFFECT" "QT_NO_STYLESHEET" "QT_NO_STYLE_CDE" "QT_NO_STYLE_CLEANLOOKS" "QT_NO_STYLE_MOTIF" "QT_NO_STYLE_PLASTIQUE" sql-drivers =  sql-plugins =  sqlite qmake switches ......... 

Build options:
  Configuration .......... accessibility audio-backend avx clock-gettime clock-monotonic compile_examples concurrent eventfd fontconfig full-config getaddrinfo getifaddrs gif iconv icu inotify ipv6ifname jpeg large-config largefile medium-config minimal-config mremap nis no-harfbuzz no-pkg-config openssl pcre png posix_fallocate precompile_header qpa qpa reduce_exports reduce_relocations release rpath small-config sse2 sse3 sse4_1 sse4_2 ssse3 static system-freetype xinput2 xlib xrender zlib 
  Build parts ............ libs
  Mode ................... release
  Using C++11 ............ no
  Using PCH .............. yes
  Target compiler supports:
    SSE2/SSE3/SSSE3 ...... yes/yes/yes
    SSE4.1/SSE4.2 ........ yes/yes
    AVX/AVX2 ............. yes/no

Qt modules and options:
  Qt D-Bus ............... no
  Qt Concurrent .......... yes
  Qt GUI ................. yes
  Qt Widgets ............. yes
  JavaScriptCore JIT ..... yes (To be decided by JavaScriptCore)
  QML debugging .......... no
  Use system proxies ..... no

Support enabled for:
  Accessibility .......... yes
  ALSA ................... no
  CUPS ................... no
  FontConfig ............. yes
  FreeType ............... system
  Iconv .................. yes
  ICU .................... yes
  Image formats: 
    GIF .................. yes (in QtGui, using bundled copy)
    JPEG ................. yes (in QtGui, using bundled copy)
    PNG .................. yes (in QtGui, using bundled copy)
  Glib ................... no
  GTK theme .............. no
  journald ............... no
  Large File ............. yes
  mtdev .................. no
  Networking: 
    getaddrinfo .......... yes
    getifaddrs ........... yes
    IPv6 ifname .......... yes
    OpenSSL .............. yes (loading libraries at run-time)
  NIS .................... yes
  EGL .................... no
  EGL on X ............... no
  GLX .................... no
  OpenGL ................. no
  OpenVG ................. no
  PCRE ................... yes (bundled copy)
  pkg-config ............. no 
  PulseAudio ............. no
  QPA backends: 
    DirectFB ............. no
    EGLFS ................ no
    KMS .................. no
    LinuxFB .............. no
    XCB .................. no
  Session management ..... no
  SQL drivers: 
    DB2 .................. no
    InterBase ............ no
    MySQL ................ no
    OCI .................. no
    ODBC ................. no
    PostgreSQL ........... no
    SQLite 2 ............. no
    SQLite ............... yes (plugin, using bundled copy)
    TDS .................. no
  udev ................... no
  xkbcommon .............. no
  zlib ................... yes (bundled copy)
```
This is the JS code I am running and giving segfault:
```js
function waitFor(testFx, onReady, timeOutMillis) {
    var maxtimeOutMillis = timeOutMillis ? timeOutMillis : 10000,
        start = new Date().getTime(),
        condition = false,
        interval = setInterval(function() {
            if ( (new Date().getTime() - start < maxtimeOutMillis) && !condition ) {
                condition = (typeof(testFx) === "string" ? eval(testFx) : testFx());
            } else {
                if(!condition) {
                    page.render("material-1983.js.png");
                    phantom.exit(2);
                } else {
                    console.log("'waitFor()' finished in " + (new Date().getTime() - start) + "ms.");
                    typeof(onReady) === "string" ? eval(onReady) : onReady();
                    clearInterval(interval);
                }
            }
        }, 1000);
};
var page = require('webpage').create();
var lastmsg = "";
page.onConsoleMessage = function(msg) {
        if (msg == lastmsg) {
                    page.render("material-1983.js.png");
                    phantom.exit(1);
        }
        lastmsg = msg;
        if (msg.search(" finished.") >= 0) {
                    page.render("material-1983.js.png");
                    phantom.exit(3);
        }
}
page.open("http://test.geogebratube.org:8080/material/iframe/id/1983/width/994/height/617/at/html5/stb/false/smb/false/ai/false/rc/false/ld/false/sri/true/sdz/true/ssg/true/", function (status) {
    if (status !== "success") {
    } else {
        waitFor(function() {
            return page.evaluate(function() {
                return $("#signin-dropdown").is(":visible");
            });
        }, function() {
           phantom.exit(0);
        });
    }
});
```
When changing "1983" everywhere to "1991", no crash happens. This latter file contains a simplified version of the canvas without any texts printed.

**Comment by kovzol** [comment]
Checked with the initial release version under Linux (compiled from source). This issue is no longer there, thanks for the fix!
