### ISSUE TITLE
PhantomJS 1.9.7 hangs intermittently

### ISSUE THREAD

**Issue by afn** [ariya/phantomjs#12234]
I'm having an intermittent issue with phantomjs 1.9.7, where it occasionally hangs while trying to load a page.  This occurs in the context of Poltergeist; see https://github.com/teampoltergeist/poltergeist/issues/375 for more background.

The symptom is that it never finishes loading the page.  The output with `--debug=true` looks like this:

```
2014-05-15T22:58:46 [DEBUG] WebPage - updateLoadingProgress: 21
2014-05-15T22:58:46 [DEBUG] CookieJar - Saved "_closing_time_session=R3Npb2VTcDJCdVpmUW1YREczT0F0Um44MDJ1aW5vT3pTb21GNkxFdjJiUlBHV1RtMGV5SUFOaFlwUlhHaUw2eDZETnpDbEpYdkMyNEVYM3BtcGg5NlE9PS0tdVF0QUVZZ29QMVBDK2VnSTZQS3lhUT09--60c661c5317a96005a7d3a4ed9740257c174e01a; HttpOnly; domain=127.0.0.1; path=/"
2014-05-15T22:58:46 [DEBUG] CookieJar - Saved "browser.timezone=Etc%2FUTC; expires=Fri, 15-May-2015 22:58:46 GMT; domain=127.0.0.1; path=/"
2014-05-15T22:58:46 [DEBUG] Network - Resource request error: 99 ( "Connection to proxy refused" ) URL: "http://widget.uservoice.com/DQpcgONtvcxXS9T8bem0iw.js"
```

Note that the "Resource request error" is expected, because we set the proxy server to an invalid host (0.0.0.0) in order to avoid dependencies on hosts other than localhost.  The bug occurs regardless of whether or not we do this, but we wanted to rule out external servers as a variable.  When phantomjs is behaving normally, it prints the same output as above, followed by `WebPage - updateLoadingProgress: 100`.

In order to debug the problem, I recompiled phantomjs from source (62fbad4814df983c973511ded476c54dc09303c9) in debug mode.

Here are the backtraces of the currently running threads:

```
(gdb) info threads
  Id   Target Id         Frame
  5    Thread 0x7f5c04691700 (LWP 12361) "phantomjs" 0x00007f5c06d47d84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
  4    Thread 0x7f5c03e90700 (LWP 12362) "QThread" 0x00007f5c06257763 in select () from /lib/x86_64-linux-gnu/libc.so.6
  3    Thread 0x7f5c018e6700 (LWP 12367) "QThread" 0x00007f5c06d47d84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
  2    Thread 0x7f5c02698700 (LWP 12564) "QThread" 0x00007f5c06257763 in select () from /lib/x86_64-linux-gnu/libc.so.6
* 1    Thread 0x7f5c08d03740 (LWP 12360) "phantomjs" 0x00007f5c06257763 in select () from /lib/x86_64-linux-gnu/libc.so.6

(gdb) thread 1
[Switching to thread 1 (Thread 0x7f5c08d03740 (LWP 12360))]
#0  0x00007f5c06257763 in select () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f5c06257763 in select () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000001d50e19 in qt_safe_select (nfds=10, fdread=0x3561c38, fdwrite=0x3561ed0, fdexcept=0x3562168, orig_timeout=0x7fff08787980) at kernel/qcore_unix.cpp:93
#2  0x0000000001d52ffa in QEventDispatcherUNIX::select (this=0x355beb0, nfds=10, readfds=0x3561c38, writefds=0x3561ed0, exceptfds=0x3562168, timeout=0x7fff08787980)
    at kernel/qeventdispatcher_unix.cpp:649
#3  0x000000000155b46c in QEventDispatcherQPA::select (this=0x355beb0, nfds=10, readfds=0x3561c38, writefds=0x3561ed0, exceptfds=0x3562168, timeout=0x7fff08787980)
    at kernel/qeventdispatcher_qpa.cpp:311
#4  0x0000000001d51a85 in QEventDispatcherUNIXPrivate::doSelect (this=0x3561a80, flags=..., timeout=0x7fff08787980) at kernel/qeventdispatcher_unix.cpp:223
#5  0x0000000001d53f86 in QEventDispatcherUNIX::processEvents (this=0x355beb0, flags=...) at kernel/qeventdispatcher_unix.cpp:936
#6  0x000000000155b16d in QEventDispatcherQPA::processEvents (this=0x355beb0, flags=...) at kernel/qeventdispatcher_qpa.cpp:246
#7  0x0000000001d20208 in QEventLoop::processEvents (this=0x7fff08787b20, flags=...) at kernel/qeventloop.cpp:149
#8  0x0000000001d20392 in QEventLoop::exec (this=0x7fff08787b20, flags=...) at kernel/qeventloop.cpp:200
#9  0x0000000001d230bb in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1221
#10 0x00000000014ed432 in QApplication::exec () at kernel/qapplication.cpp:3823
#11 0x0000000000424d4e in main (argc=8, argv=0x7fff08787dc8, envp=0x7fff08787e10) at main.cpp:121

(gdb) thread 2
[Switching to thread 2 (Thread 0x7f5c02698700 (LWP 12564))]
#0  0x00007f5c06257763 in select () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f5c06257763 in select () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000001d50e19 in qt_safe_select (nfds=20, fdread=0x7f5bb401c6c8, fdwrite=0x7f5bb401c960, fdexcept=0x7f5bb401cbf8, orig_timeout=0x7f5c02697c50) at kernel/qcore_unix.cpp:93
#2  0x0000000001d52ffa in QEventDispatcherUNIX::select (this=0x7f5bb4001650, nfds=20, readfds=0x7f5bb401c6c8, writefds=0x7f5bb401c960, exceptfds=0x7f5bb401cbf8,
    timeout=0x7f5c02697c50) at kernel/qeventdispatcher_unix.cpp:649
#3  0x0000000001d51a85 in QEventDispatcherUNIXPrivate::doSelect (this=0x7f5bb401c510, flags=..., timeout=0x7f5c02697c50) at kernel/qeventdispatcher_unix.cpp:223
#4  0x0000000001d53f86 in QEventDispatcherUNIX::processEvents (this=0x7f5bb4001650, flags=...) at kernel/qeventdispatcher_unix.cpp:936
#5  0x0000000001d20208 in QEventLoop::processEvents (this=0x7f5c02697db0, flags=...) at kernel/qeventloop.cpp:149
#6  0x0000000001d20392 in QEventLoop::exec (this=0x7f5c02697db0, flags=...) at kernel/qeventloop.cpp:200
#7  0x0000000001c1586b in QThread::exec (this=0x4dc51a0) at thread/qthread.cpp:536
#8  0x0000000001c15a0a in QThread::run (this=0x4dc51a0) at thread/qthread.cpp:603
#9  0x0000000001c17fbb in QThreadPrivate::start (arg=0x4dc51a0) at thread/qthread_unix.cpp:338
#10 0x00007f5c06d43e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#11 0x00007f5c0625e3fd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#12 0x0000000000000000 in ?? ()

(gdb) thread 3
[Switching to thread 3 (Thread 0x7f5c018e6700 (LWP 12367))]
#0  0x00007f5c06d47d84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) bt
#0  0x00007f5c06d47d84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000000001c195df in QWaitConditionPrivate::wait (this=0x38e58f0, time=18446744073709551615) at thread/qwaitcondition_unix.cpp:86
#2  0x0000000001c19389 in QWaitCondition::wait (this=0x38d9e50, mutex=0x38ce860, time=18446744073709551615) at thread/qwaitcondition_unix.cpp:158
#3  0x00000000004ea5e8 in WTF::ThreadCondition::wait(WTF::Mutex&) ()
#4  0x00000000004ea651 in WTF::ThreadCondition::timedWait(WTF::Mutex&, double) ()
#5  0x000000000110fcba in WTF::PassOwnPtr<WebCore::LocalStorageTask> WTF::MessageQueue<WebCore::LocalStorageTask>::waitForMessageFilteredWithTimeout<bool (WebCore::LocalStorageTask*)>(WTF::MessageQueueWaitResult&, bool (&)(WebCore::LocalStorageTask*), double) ()
#6  0x000000000110f81d in WTF::MessageQueue<WebCore::LocalStorageTask>::waitForMessage() ()
#7  0x000000000110f4d5 in WebCore::LocalStorageThread::threadEntryPoint() ()
#8  0x000000000110f4ac in WebCore::LocalStorageThread::threadEntryPointCallback(void*) ()
#9  0x0000000000e90863 in WTF::threadEntryPoint(void*) ()
#10 0x00000000004e9dbb in WTF::ThreadPrivate::run() ()
#11 0x0000000001c17fbb in QThreadPrivate::start (arg=0x389df40) at thread/qthread_unix.cpp:338
#12 0x00007f5c06d43e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#13 0x00007f5c0625e3fd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#14 0x0000000000000000 in ?? ()

(gdb) thread 4
[Switching to thread 4 (Thread 0x7f5c03e90700 (LWP 12362))]
#0  0x00007f5c06257763 in select () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007f5c06257763 in select () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000001d50d99 in qt_safe_select (nfds=8, fdread=0x7f5bfc000a98, fdwrite=0x7f5bfc000d30, fdexcept=0x7f5bfc000fc8, orig_timeout=0x0) at kernel/qcore_unix.cpp:83
#2  0x0000000001d52ffa in QEventDispatcherUNIX::select (this=0x7f5bfc0008c0, nfds=8, readfds=0x7f5bfc000a98, writefds=0x7f5bfc000d30, exceptfds=0x7f5bfc000fc8, timeout=0x0)
    at kernel/qeventdispatcher_unix.cpp:649
#3  0x0000000001d51a85 in QEventDispatcherUNIXPrivate::doSelect (this=0x7f5bfc0008e0, flags=..., timeout=0x0) at kernel/qeventdispatcher_unix.cpp:223
#4  0x0000000001d53f86 in QEventDispatcherUNIX::processEvents (this=0x7f5bfc0008c0, flags=...) at kernel/qeventdispatcher_unix.cpp:936
#5  0x0000000001d20208 in QEventLoop::processEvents (this=0x7f5c03e8fdb0, flags=...) at kernel/qeventloop.cpp:149
#6  0x0000000001d20392 in QEventLoop::exec (this=0x7f5c03e8fdb0, flags=...) at kernel/qeventloop.cpp:200
#7  0x0000000001c1586b in QThread::exec (this=0x35a2e40) at thread/qthread.cpp:536
#8  0x0000000001c15a0a in QThread::run (this=0x35a2e40) at thread/qthread.cpp:603
#9  0x0000000001c17fbb in QThreadPrivate::start (arg=0x35a2e40) at thread/qthread_unix.cpp:338
#10 0x00007f5c06d43e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#11 0x00007f5c0625e3fd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#12 0x0000000000000000 in ?? ()

(gdb) thread 5
[Switching to thread 5 (Thread 0x7f5c04691700 (LWP 12361))]
#0  0x00007f5c06d47d84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) bt
#0  0x00007f5c06d47d84 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00000000004e381b in WTF::TCMalloc_PageHeap::scavengerThread() ()
#2  0x00000000004e23ac in WTF::TCMalloc_PageHeap::runScavengerThread(void*) ()
#3  0x00007f5c06d43e9a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007f5c0625e3fd in clone () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x0000000000000000 in ?? ()
```

Any idea what's going wrong?  I'll start digging into the source myself, but hopefully you're able to find the bug sooner than I. :)

Best,
Tony

**Comment by cyrilchampier** [comment]
+1

**Comment by rschooley** [comment]
This is still a problem.

**Comment by Vitallium** [comment]
@rschooley could you please elaborate more on this? Version? 1.9.7? Try 1.9.8 or 2.0. OS?

**Comment by rschooley** [comment]
@Vitallium please see @afn's info, he has provided a comprehensive look at the issue.  I am merely reporting that this still happens.

**Comment by andela-bolanrewaju** [comment]
@Vitallium for me, the issue still exist. I'm using phamtomjs 1.9.8, OS 10.10 (Yosemite). I've tried everything stated here except the part of retrying the test after restarting phantomjs. 

Using phantomjs 2.0 gives non-deterministic random test failures. Would love if anyone could offer help in getting this to work, most especially on CircleCI

**Comment by Vitallium** [comment]
@andela-bolanrewaju could you please provide a minimal test case?

**Comment by Vitallium** [comment]
@rschooley without a minimal _working_ test case I can't do much.

**Comment by rschooley** [comment]
@Vitallium I can't provide more than @afn already has, please see his verbose explanation

**Comment by RomanKapitonov** [comment]
The same issue for me

**Comment by lifeboatpres** [comment]
I rarely (less than 1% of the time) get a hang from PhantomJS when loading a page. I'm not waiting for the page to completely load, my short script tells it to stop loading after 8 seconds. I'm running PhantomJS 2.01 on Centos 6.6. I happened to get into a situation where it was hanging consistently on one site and I fixed it by calling PhantomJS with --debug=true. Note that once I had stopped the hanging problem, then I was able to get it to work at that same site without setting the debug option. Anyway, this is a workaround that may be useful to some people. (I redirect the massive amount of debug messages it produces to /dev/null.)

**Comment by jsarenik** [comment]
Hanging on CircleCI for me as well. Is there any progress? Was the main reason found yet? Thanks!

**Comment by dre-hh** [comment]
same issue here. visiting sites gives a timeout. However if you just ignore the error, the site is rendered correctly

**Comment by CoreySwish** [comment]
+1 on Ubuntu 14.04, I have a script running every 2 hours, sometimes it closes properly and others it does not. Brings the cpu util up to 80% and i have to kill the hanging jobs b4 it, basically, locks the server up.

**Comment by oncletom** [comment]
I encounter some similar issue, a workaround:

```bash
timeout -k 5s 30s phantomjs script.js
```

It will force kill the process 5 seconds after a timeout of 30 seconds.

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2 version.

**Comment by criticerz** [comment]
Upgrading to 2.1.1 fixed the timeout issue for me.

**Comment by jjb** [comment]
I still experience this issue with 2.1.1.
