### ISSUE TITLE
Not able to start PhantomJS 1.9.8 on CentOS 5.10

### ISSUE THREAD

**Issue by elmabp** [ariya/phantomjs#12907]
I have tried with selenium 2.39 and 2.42.2.
It is working properly on Windows 7 and Linux Mint

I am getting this error:

Jan 25, 2015 4:59:03 PM org.openqa.grid.selenium.GridLauncher main
INFO: Launching a standalone server
16:59:03.866 INFO - Java: Oracle Corporation 24.72-b04
16:59:03.877 INFO - OS: Linux 2.6.18-371.3.1.el5 amd64
16:59:03.893 INFO - v2.42.2, with Core v2.42.2. Built from revision 6a6995d
16:59:04.037 INFO - Default driver org.openqa.selenium.ie.InternetExplorerDriver registration is skipped: registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match with current platform: LINUX
16:59:04.083 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
16:59:04.084 INFO - Version Jetty/5.1.x
16:59:04.085 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
16:59:04.086 INFO - Started HttpContext[/selenium-server,/selenium-server]
16:59:04.086 INFO - Started HttpContext[/,/]
16:59:04.177 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@24e0a659
16:59:04.178 INFO - Started HttpContext[/wd,/wd]
16:59:04.188 INFO - Started SocketListener on 0.0.0.0:4444
16:59:04.189 INFO - Started org.openqa.jetty.jetty.Server@295cd6e5
17:00:07.611 INFO - Executing: [new session: Capabilities [{platform=ANY, javascriptEnabled=true, phantomjs.cli.args=[--web-security=false, --ssl-protocol=any, --ignore-ssl-errors=true], browserName=phantomjs, phantomjs.ghostdriver.cli.args=[--logLevel=2], phantomjs.binary.path=/home/web/domains/infiniteprofitsolutions.com/automted_testing/phantomjs, takesScreenshot=true, version=}]])
17:00:07.649 INFO - Creating a new session for Capabilities [{platform=ANY, javascriptEnabled=true, phantomjs.cli.args=[--web-security=false, --ssl-protocol=any, --ignore-ssl-errors=true], browserName=phantomjs, phantomjs.ghostdriver.cli.args=[--logLevel=2], phantomjs.binary.path=/home/web/domains/infiniteprofitsolutions.com/automted_testing/phantomjs, takesScreenshot=true, version=}]
17:00:07.658 INFO - executable: /home/web/domains/infiniteprofitsolutions.com/automted_testing/phantomjs
17:00:07.658 INFO - port: 3428
17:00:07.658 INFO - arguments: [--web-security=false, --ssl-protocol=any, --ignore-ssl-errors=true, --webdriver=3428, --webdriver-logfile=/home/web/phantomjsdriver.log]
17:00:07.658 INFO - environment: {}
17:00:28.048 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:03'
System info: host: 'ss0454.svwh.net', ip: '108.17.240.98', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.18-371.3.1.el5', java.version: '1.7.0_72'
Driver info: driver.version: unknown
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
	at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:176)
	at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:112)
	at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:89)
	at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:110)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:57)
	at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:1)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:112)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:173)
	at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:200)
	at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:162)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.openqa.selenium.remote.server.DriverServlet.service(DriverServlet.java:128)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:680)
	at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:571)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1526)
	at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1479)
	at org.openqa.jetty.http.HttpServer.service(HttpServer.java:920)
	at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
	at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
	at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
	at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:358)
	at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:537)
Caused by: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:03'
System info: host: 'ss0454.svwh.net', ip: '108.17.240.98', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.18-371.3.1.el5', java.version: '1.7.0_72'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:69)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.newInstance(DefaultDriverProvider.java:53)
	at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:54)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:215)
	at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:169)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.server.DefaultDriverProvider.callConstructor(DefaultDriverProvider.java:59)
	... 9 more
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:03'
System info: host: 'ss0454.svwh.net', ip: '108.17.240.98', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.18-371.3.1.el5', java.version: '1.7.0_72'
Driver info: driver.version: PhantomJSDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:593)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:139)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:110)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:99)
	... 14 more
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:03'
System info: host: 'ss0454.svwh.net', ip: '108.17.240.98', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.18-371.3.1.el5', java.version: '1.7.0_72'
Driver info: driver.version: PhantomJSDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:165)
	at org.openqa.selenium.phantomjs.PhantomJSCommandExecutor.execute(PhantomJSCommandExecutor.java:78)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	... 19 more
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:3428/status to be available after 20002 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:104)
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:163)
	... 21 more
Caused by: com.google.common.util.concurrent.UncheckedTimeoutException: java.util.concurrent.TimeoutException
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:143)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:79)
	... 22 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:130)
	... 23 more
17:00:28.056 WARN - Exception: null

**Comment by elmabp** [comment]
I have resolved the issue by compiling phantomjs file from source code.
