### ISSUE TITLE
PhantomJS crashes at times during Test execution 

### ISSUE THREAD

**Issue by MadhuCTS** [ariya/phantomjs#12922]
With increase of number of tests(170) , I see the below exception at times. Initially with less number of tests, i didn't face the issue. Using Parallel execution with thread count  as 3.

02:34:34 PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/417e7682-a008-9dde-72acd7bc-6c93914c.dmp

Stacktrace

org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.42.2', revision: '6a6995d31c7c56c340d6f45a76976d43506cd6cc', time: '2014-06-03 10:52:47'
System info: host: 'fdsqn1vpbldap01', ip: '10.208.58.31', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-431.el6.x86_64', java.version: '1.7.0_21'
Driver info: driver.version: RemoteWebDriver
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391)
    at java.net.Socket.connect(Socket.java:579)
    at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
    at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
    at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
    at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
    at org.openqa.selenium.remote.HttpCommandExecutor.fallBackExecute(HttpCommandExecutor.java:337)
    at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:298)
    at org.openqa.selenium.phantomjs.PhantomJSCommandExecutor.execute(PhantomJSCommandExecutor.java:82)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:527)
    at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
    at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79)
    at com.corelogic.xianceweb.test.selenium.batch.BatchAddressPhantomJSTestCase.uploadFile(BatchAddressPhantomJSTestCase.java:838)

**Comment by garimacha** [comment]
Not sure if my problem is same or not but this is the stack trace -

org.openqa.selenium.TimeoutException: Timed out after 15 seconds waiting for condition (visibility of element located by By.className: creNumberLabel) to be refreshed
Build info: version: '2.40.0', revision: '4c5c0568b004f67810ee41c459549aa4b09c651e', time: '2014-02-19 11:13:01'
System info: host: 'noarddvbld10.noa.nintendo.com', ip: '10.1.65.105', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.39-400.21.2.el6uek.x86_64', java.version: '1.7.0_51'
Driver info: driver.version: unknown
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:125)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:573)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:326)
    at org.openqa.selenium.remote.RemoteWebDriver.findElementByClassName(RemoteWebDriver.java:407)
    at org.openqa.selenium.By$ByClassName.findElement(By.java:387)
    at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:318)
    at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:730)
    at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:39)
    at org.openqa.selenium.support.ui.ExpectedConditions$4.apply(ExpectedConditions.java:130)
    at org.openqa.selenium.support.ui.ExpectedConditions$4.apply(ExpectedConditions.java:126)
    at org.openqa.selenium.support.ui.ExpectedConditions$20.apply(ExpectedConditions.java:625)
    at org.openqa.selenium.support.ui.ExpectedConditions$20.apply(ExpectedConditions.java:621)
    at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)

**Comment by MadhuCTS** [comment]
StackTrace of above crash dump file: /tmp/417e7682-a008-9dde-72acd7bc-6c93914c.dmp , which had actually created in linux.


Microsoft (R) Windows Debugger Version 6.12.0002.633 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [D:\XianceBacklogs\417e7682-a008-9dde-72acd7bc-6c93914c.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

64-bit machine not using 64-bit API
Symbol search path is: C:\Symbols
Executable search path is: 
Unknown System Version 0 (Linux 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64) MP (2 procs) Free x64
Machine Name:
Debug session time: Thu Jan 29 14:04:34.000 2015 (UTC + 5:30)
System Uptime: not available
Process Uptime: not available
..................................
The call to LoadLibrary(ext) failed, Win32 error 0n2
    "The system cannot find the file specified."
Please check your debugger configuration and/or network access.
The call to LoadLibrary(uext) failed, Win32 error 0n2
    "The system cannot find the file specified."
Please check your debugger configuration and/or network access.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(f0f0f0f0.c32d): Unknown exception - code 0000000b (first/second chance not available)
00007f87`001d40ee 488b40c8        mov     rax,qword ptr [rax-38h] ds:ffffffff`ffffffc8=????????????????

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://pikeplumbingnc.com/jew.php?vi>

 

klaus@hebsgaard.dk
