### ISSUE TITLE
WebDriverWait foundation modal not found

### ISSUE THREAD

**Issue by cyber778** [ariya/phantomjs#13172]
Hello,

I have this code (using django):

``` python
    from selenium.webdriver.phantomjs.webdriver import WebDriver
    #from selenium.webdriver.firefox.webdriver import WebDriver -> this works when uncommented

    modal_button = self.selenium.find_element_by_id("myModalBtn")
    modal_button.click()

    WebDriverWait(self.selenium, CLIENT_ACTION_TIMEOUT).until(
        ec.visibility_of_element_located((By.ID, "editCategoryModal"))
    )
```

this code works with ff, but with phantom.js I get TimeoutException

I have my window size set to 1920 x 1080 so that isn't the problem
I also tried to get element by class name
I also tried raising the CLIENT_ACTION_TIMEOUT time
tried explicit_wait()
tried time.sleep

searched all forums with no answer

as a last resort i'm opening this ticket

**Comment by leenabora** [comment]
Hi,

I am also facing exactly the same issue. As we are blocked on it Quick soln will be appreciated.

**Comment by zackw** [comment]
Thank you for your bug report.  Unfortunately, I can't do anything with it as is; I need a *complete* Selenium script and matching webpage to run it against.  If I made up a webpage, filled in the missing pieces of your script, and tried it, I probably wouldn't see the bug!

Regardless, I regret to say that we do not have a quick solution for you.  I myself gave up on Selenium precisely because of problems like this.

**Comment by cyber778** [comment]
OK it took me a while but I made the simplest test page displaying the bug:
###### Using django 1.7.5 and phanthomjs 1.9.8

### this is my set up and teardown:

```python
from selenium.webdriver.common.by import By
from selenium.webdriver.phantomjs.webdriver import WebDriver
from selenium.webdriver.support.ui import WebDriverWait

from main.test_utils import BaseClientTestCase

DEBUG_TIMEOUT = 30
SERVER_REQUEST_TIMEOUT = 10
CLIENT_ACTION_TIMEOUT = 1
TEST_USER_LOGIN = "labtest@devcomm.com"
TEST_USER_PWD = "123"


class ClientTestCase(BaseClientTestCase):
    """ ClientTestCase """

    def setUp(self):
        """ ClientTestCase setUp - prepares driver for testing: opens web app and logs in
        """
        # create_initial_data()
        self.selenium = WebDriver()
        self.selenium.set_window_size(1920, 1080)
        super(ClientTestCase, self).setUp()

        self.selenium.get("%s/accounts/login/" % self.live_server_url)
        super(ClientTestCase, self).wait_for_id("LoginForm")
        self.selenium.find_element_by_id("login").send_keys(TEST_USER_LOGIN)
        self.selenium.find_element_by_id("password").send_keys(TEST_USER_PWD)
        WebDriverWait(self.selenium, CLIENT_ACTION_TIMEOUT)
        self.selenium.find_element_by_id("submit").click()
        super(ClientTestCase, self).wait_for_id("main_region")

    def tearDown(self):
        """ ClientTestCase tearDown """
        # Closes the driver
        self.selenium.quit()
        super(ClientTestCase, self).tearDown()
```

### this is my test case:

```python
from main.tests.test_client import ClientTestCase as MainClientTestCase
from organizations.models import Customer

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec

import time
CLIENT_ACTION_TIMEOUT = 5


class ClientTestCase(MainClientTestCase):
    """ ClientTestCase """

    # TODO: uncomment when ticker is resolved: https://github.com/ariya/phantomjs/issues/13172

    def test_modal(self):
        """
        ClientTestCase test_modal
        uses foundation modal
        """
        customer = Customer.objects.all()[0]
        self.selenium.get("%s/test/"%self.live_server_url)
        WebDriverWait(self.selenium, CLIENT_ACTION_TIMEOUT).until(
            ec.visibility_of_element_located((By.ID, "modalBtn"))
        )

        add_btn = self.selenium.find_element_by_id("modalBtn")
        add_btn.click()
        # this doesn't work in ghost.js
        WebDriverWait(self.selenium, CLIENT_ACTION_TIMEOUT).until(
            ec.visibility_of_element_located((By.ID, "myModal"))
        )

```

### And this is my html:

```html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/css/foundation.css"/>
    <title>test</title>
</head>
<body>
<div>
    <a href="#" id="modalBtn" data-reveal-id="myModal">Click Me For A Modal</a>

    <div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
      <h2 id="modalTitle">Awesome. I have it.</h2>
      <p class="lead">Your couch.  It is mine.</p>
      <p>I'm a cool paragraph that lives inside of an even cooler modal. Wins!</p>
      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>
</div>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.3.0/js/foundation.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.3.0/js/foundation/foundation.reveal.js"></script>
<script>
    $(document).foundation();
</script>
</body>
</html>
```

### this is my exception:

``` bash
ERROR: test_modal (rules.tests.test_client.ClientTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rnd/pluto/rules/tests/test_client.py", line 33, in test_modal
    ec.visibility_of_element_located((By.ID, "myModal"))
  File "/home/rnd/pypy/local/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 75, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message: 


```

**Comment by cyber778** [comment]
Hi @zackw , I want to be as helpful as I can and i wanted to know was the supplied information above enough?
