### ISSUE TITLE
I can't upload file when use Selenium WebDriver PhantomJS bridge

### ISSUE THREAD

**Issue by tit** [ariya/phantomjs#13191]
I use Ruby Selenium WebDriver with PhantomJS bridge.
```
driver = Selenium::WebDriver.for :phantomjs
driver.get 'example.com'
element = driver.find_element :xpath, '//*[@id="upload"]'
element.send_keys '/tmp/filename'
```

But script is crashed. Why?
In Chrome (Selenium::WebDriver.for :chrome) work normal.
```
Net::ReadTimeout: Net::ReadTimeout
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1406:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/default.rb:83:in `response_for'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/default.rb:39:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:417:in `sendKeysToElement'
	from /Library/Ruby/Gems/2.0.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/element.rb:126:in `send_keys'
	from (irb):23
	from /usr/bin/irb:12:in `<main>'irb(main):024:0> ^D
```

**Comment by Nek-** [comment]
What version of phantomjs ?

**Comment by tit** [comment]
2.0.0

**Comment by Nek-** [comment]
Well, this is related to #12506 and fixed here: https://github.com/ariya/phantomjs/issues/12506#issuecomment-61698339

**Comment by tit** [comment]
Sorry for my stupid question, but, where I can download last version of PhantomJS with this patch?
My port (macports) say: 
```
$ port search phantomjs
phantomjs @2.0.0 (www)
    PhantomJS is a minimalistic headless WebKit.
```

**Comment by Nek-** [comment]
Nowhere, you need to compile it for now after added the modification by hand. You can use the branch 2.0 for that.

**Comment by tit** [comment]
Thanx. Now I understood you.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://ezicliq.com/location.php?8x5sw>

 

klaus@hebsgaard.dk
