### ISSUE TITLE
Code breaks in Phantom but not Chrome/FF

### ISSUE THREAD

**Issue by Zensavona** [ariya/phantomjs#13205]
Hi guys, I'm trying to get my code running in Phantom to run some tests, but it's breaking and I'm not exactly sure why.

It's an Aurelia/SystemJS based app and both my application and an Aurelia example using SystemJS break with Phantom. Here are the outputs from both:

[app-contacts](https://github.com/aurelia/app-contacts):

````
CONSOLE: INFO [aurelia] Aurelia Starting (from line #undefined in "undefined")
CONSOLE: DEBUG [aurelia] Loading plugin github:aurelia/templating-binding@0.11.0. (from line #undefined in "undefined")
TypeError: Attempting to define property on object that is not extensible.

  http://localhost:9001/:48 in defineProperty
  http://localhost:9001/:36
  http://localhost:9001/:29 in fastKey
  http://localhost:9001/:115
  http://localhost:9001/:10 in set
  http://localhost:9001/:51 in set
  http://localhost:9001/:14 in ensureOriginOnExports
  http://localhost:9001/:131
  http://localhost:9001/jspm_packages/es6-module-loader.js:7 in O
  http://localhost:9001/jspm_packages/es6-module-loader.js:7 in K
  http://localhost:9001/jspm_packages/es6-module-loader.js:7
  http://localhost:9001/jspm_packages/es6-module-loader.js:7
  http://localhost:9001/jspm_packages/es6-module-loader.js:7
  http://localhost:9001/jspm_packages/es6-module-loader.js:7
````

my application:

````
CONSOLE: Potentially unhandled rejection [2] ReferenceError: Can't find variable: Map
    at http://127.0.0.1:8380/web-admin/:22
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1)
    at http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1
    at o (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at j (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at k (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7
    at O (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at K (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7)
    at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7
    at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7
    at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7
    at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7 (from line #undefined in "undefined")
````
FWIW these both work fine in Chrome/FF and I'm running PhantomJS 1.9.8 on OS X 10.10

Also here's the phantom script I am using to test these and output from the console:
````
var webPage = require('webpage');
var page = webPage.create();

page.open('http://localhost:9001/', function() {
  page.onConsoleMessage = function(msg, lineNum, sourceId) {
    console.log('CONSOLE: ' + msg + ' (from line #' + lineNum + ' in "' + sourceId + '")');
  };
});
````

I've made some instructions to replicate the first set of errors:
````
git clone git@github.com:aurelia/app-contacts.git
cd app-contacts
npm install && jspm install
gulp watch
````
This assumes you have `node`, `jspm` and `gulp` installed. Then you can run the above phantomjs script.

**Comment by Vitallium** [comment]
Aurelia written with ES6 and ES7. PhantomJS 1.x doesn't support neither ES6 nor ES7. I think you should give a try to 2.x version.

**Comment by Zensavona** [comment]
Thanks for the response @Vitallium, my code is transpiled to ES5 with 6to5/traceur before hitting the browser (and so is the example above I believe).

Is there a way to install `2.0.0` with npm? I've been trying all morning but it's not listed on npm (only up to 1.9.16) and when I try listing `github:ariya/phantomjs.git@2.0.0` or `github:ariya/phantomjs.git#v2.0.0` I get a similar error. I also tried using `https://github.com/ariya/phantomjs/archive/2.0.0.tar.gz` but npm complains that there isn't a valid `package.json'.

**Comment by Zensavona** [comment]
nvm @Vitallium, I got PhantomJS 2 running (phantomjs2 npm package, who would of thought...) and am now getting an even more cryptic error.

````
Potentially unhandled rejection [2]     at execute (http://127.0.0.1:8380/web-admin/:22:30)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9364)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:9296)
    at execute (http://127.0.0.1:8380/web-admin/jspm_packages/system.js:1:18339)
    at o (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:44413)
    at p (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:44779)
    at j (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:42325)
    at k (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:42710)
    at http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:55365
    at O (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:12117)
    at K (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:11746)
    at when (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:15420)
    at run (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:14459)
    at _drain (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:3232)
    at drain (http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7:1653)

  http://127.0.0.1:8380/web-admin/jspm_packages/es6-module-loader.js:7
````

**Comment by mdix** [comment]
Havin a similar issue using a module ([stampit](https://github.com/stampit-org/stampit)) written in ES6. Works fine with Chrome, but not Phantomjs 1.9.8.

**Comment by binarydev** [comment]
@mdix You should also upgrade from 1.9.8 to 2.0, which has better but not perfect ES6 support.

Having an issue myself with WeakMap not working in phantomjs but working fine in Chrome/Firefox

**Comment by mdix** [comment]
@binarydev Thanks for the hint. I switched to 2.0 four days ago. Works gr8 locally, but breaks on Travis. Reported it [here](https://github.com/gskachkov/phantomjs2/issues/7), let's see.

**Comment by zackw** [comment]
It sounds like everything that's left to do here involves NPM and/or Travis, so I'm going to close this issue.  Please file a new bug if there are remaining problems.
