### ISSUE TITLE
select: Invalid argument

### ISSUE THREAD

**Issue by corysimmons** [ariya/phantomjs#13231]
When running a handful of documents through UnCSS it seems to work fine, but when I try to run hundreds through it, I start getting hundreds of these errors followed by an unspecified PhantomJS error.

```
...
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
phantomjs(35781,0x11f2ab000) malloc: *** error for object 0x1049b6f60: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument

/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                                 ^
Error: Cannot load http://dev.foo.org/cats/kittens/: Phantomjs returned status fail
    at reject (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/phantom/start.js:71)
    at onPageLoaded (:4)
    at :/modules/webpage.js:281
    -----------------------------------------------------------------------
    at Phantom._send (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/Phantom.js:165:20)
    at Page.run (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/Page.js:62:25)
    at Phantom.openPage (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/Phantom.js:123:17)
    at Object.fromRemote (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/src/phantom.js:148:20)
    at /Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/src/uncss.js:41:28
    at tryCatcher (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/util.js:24:31)
    at MappingPromiseArray._promiseFulfilled (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/map.js:54:38)
    at MappingPromiseArray.init [as _init$] (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise_array.js:92:18)
    at MappingPromiseArray.init (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/map.js:27:23)
    at Async._drainQueue (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

Can anyone tell me what's up with this? I'm new to PhantomJS/UnCSS.

**Comment by dylee** [comment]
+1

**Comment by corysimmons** [comment]
I don't suspect this will get answered. 1500+ open issues.
