### ISSUE TITLE
1.9.8 Crash on server in FIPS mode

### ISSUE THREAD

**Issue by kss86** [ariya/phantomjs#13299]
**Error:**

fips.c(152): OpenSSL internal error, assertion failed: FATAL FIPS SELFTEST FAILURE
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/6a6322a9-47b7-4f86-24429c4a-72de7e1c.dmp
Aborted

**GDB backtrace:**
```
fips.c(152): OpenSSL internal error, assertion failed: FATAL FIPS SELFTEST FAILURE

Program received signal SIGABRT, Aborted.
0x00002aaaabf6cfc5 in raise () from /lib64/libc.so.6
(gdb) backtrace
#0  0x00002aaaabf6cfc5 in raise () from /lib64/libc.so.6
#1  0x00002aaaabf6ea70 in abort () from /lib64/libc.so.6
#2  0x00002aaaafb9714f in OpenSSLDie () from /usr/lib64/libcrypto.so
#3  0x00002aaaafb99d91 in EVP_DigestUpdate () from /usr/lib64/libcrypto.so
#4  0x00002aaaafb9c898 in ?? () from /usr/lib64/libcrypto.so
#5  0x00002aaaafb9dba1 in RAND_poll () from /usr/lib64/libcrypto.so
#6  0x00002aaaafb9c64b in ?? () from /usr/lib64/libcrypto.so
#7  0x0000000001b9b57f in QSslSocketPrivate::ensureLibraryLoaded () at ssl/qsslsocket_openssl.cpp:543
#8  0x0000000001b9b679 in QSslSocketPrivate::supportsSsl () at ssl/qsslsocket_openssl.cpp:521
#9  0x0000000001b940a9 in QSslSocket::supportsSsl () at ssl/qsslsocket.cpp:1598
#10 0x0000000000427d85 in main (argc=1, argv=0x7fffffffe858, envp=0x7fffffffe868) at main.cpp:110
```
**Work Around:**

Need to prevent from running  q_RAND_status(),
```
// Initialize OpenSSL's random seed.
        if (!q_RAND_status()) {
```
 just return true before any of that..... 
Dont know what ramifications are to this, but it runs and works after this change.

```
diff --git a/src/qt/src/network/ssl/qsslsocket_openssl.cpp b/src/qt/src/network/ssl/qsslsocket_openssl.cpp
index b7ca290..e0a5a3f 100644
--- a/src/qt/src/network/ssl/qsslsocket_openssl.cpp
+++ b/src/qt/src/network/ssl/qsslsocket_openssl.cpp
@@ -523,6 +523,7 @@ bool QSslSocketPrivate::supportsSsl()
 
 bool QSslSocketPrivate::ensureLibraryLoaded()
 {
+    return true;
     if (!q_resolveOpenSslSymbols())
         return false;
 ```

Rebuilt from source after this. Worked fine.

**Mini-dump:**

```
Operating system: Linux
                  0.0.0 Linux 2.6.18-400.1.1.el5 #1 SMP Sun Dec 14 06:01:17 EST 2014 x86_64
CPU: amd64
     family 6 model 37 stepping 1
     24 CPUs

Crash reason:  SIGABRT
Crash address: 0x2b8006e2000076cc

Thread 0 (crashed)
 0  libc-2.5.so + 0x2ffc5
    rbx = 0x00007fff2b238850   r12 = 0x00007fff2b238950
    r13 = 0x00007fff2b238980   r14 = 0x00002b2f6a9816a0
    r15 = 0x00007fff2b238950   rip = 0x00002b2f66adcfc5
    rsp = 0x00007fff2b2387a8   rbp = 0x00002b2f6702ae90
    Found by: given as instruction pointer in context
 1  libc-2.5.so + 0x31a6f
    rip = 0x00002b2f66adea70   rsp = 0x00007fff2b2387b0
    Found by: stack scanning
 2  libc-2.5.so + 0x35385f
    rip = 0x00002b2f66e00860   rsp = 0x00007fff2b2387c0
    Found by: stack scanning
 3  libc-2.5.so + 0xe88c6
    rip = 0x00002b2f66b958c7   rsp = 0x00007fff2b2387f0
    Found by: stack scanning
 4  libc-2.5.so + 0x67d7
    rip = 0x00002b2f66ab37d8   rsp = 0x00007fff2b238808
    Found by: stack scanning
 5  libcrypto.so.0.9.8e + 0xd614e
    rip = 0x00002b2f6a70714f   rsp = 0x00007fff2b2388f0
    Found by: stack scanning
 6  libcrypto.so.0.9.8e + 0xd8d90
    rip = 0x00002b2f6a709d91   rsp = 0x00007fff2b238900
    Found by: stack scanning
 7  libcrypto.so.0.9.8e + 0xdb897
    rip = 0x00002b2f6a70c898   rsp = 0x00007fff2b238920
    Found by: stack scanning
 8  libcrypto.so.0.9.8e + 0x32fd9f
    rip = 0x00002b2f6a960da0   rsp = 0x00007fff2b238958
    Found by: stack scanning
 9  libcrypto.so.0.9.8e + 0xdcba0
    rip = 0x00002b2f6a70dba1   rsp = 0x00007fff2b2389e0
    Found by: stack scanning
10  libcrypto.so.0.9.8e + 0x3308a7
    rip = 0x00002b2f6a9618a8   rsp = 0x00007fff2b238a10
    Found by: stack scanning

Loaded modules:
0x00400000 - 0x0268dfff  phantomjs-linux  ???  (main)
0x2b2f6561b000 - 0x2b2f65636fff  ld-2.5.so  ???
0x2b2f65839000 - 0x2b2f65abcfff  libfreetype.so.6.3.10  ???
0x2b2f65abd000 - 0x2b2f65ceffff  libfontconfig.so.1.1.0  ???
0x2b2f65cf1000 - 0x2b2f65ef4fff  libdl-2.5.so  ???
0x2b2f65ef6000 - 0x2b2f660fefff  librt-2.5.so  ???
0x2b2f660ff000 - 0x2b2f66316fff  libpthread-2.5.so  ???
0x2b2f6631b000 - 0x2b2f66608fff  libstdc++.so.6.0.8  ???
0x2b2f6661c000 - 0x2b2f6689efff  libm-2.5.so  ???
0x2b2f6689f000 - 0x2b2f66aacfff  libgcc_s-4.1.2-20080825.so.1  ???
0x2b2f66aad000 - 0x2b2f66e00fff  libc-2.5.so  ???
0x2b2f66e07000 - 0x2b2f67029fff  libexpat.so.0.5.0  ???
0x2b2f6702c000 - 0x2b2f6a5f7fff  locale-archive  ???
0x2b2f6a5f8000 - 0x2b2f6a5fefff  beeeeb3dfe132a8a0633a017c99ce0c0-x86-64.cache-2  ???
0x2b2f6a5ff000 - 0x2b2f6a609fff  e19de935dec46bbf3ed114ee4965548a-x86-64.cache-2  ???
0x2b2f6a60a000 - 0x2b2f6a60cfff  e3ead4b767b8819993a6fa3ae306afa9-x86-64.cache-2  ???
0x2b2f6a60d000 - 0x2b2f6a610fff  b67b32625a2bb51b023d3814a918f351-x86-64.cache-2  ???
0x2b2f6a611000 - 0x2b2f6a618fff  b79f3aaa7d385a141ab53ec885cc22a8-x86-64.cache-2  ???
0x2b2f6a619000 - 0x2b2f6a61afff  87f5e051180a7a75f16eb6fe7dbd3749-x86-64.cache-2  ???
0x2b2f6a631000 - 0x2b2f6a97dfff  libcrypto.so.0.9.8e  ???
0x2b2f6a982000 - 0x2b2f6ab95fff  libz.so.1.2.3  ???
0x2b2f6ab96000 - 0x2b2f6ade3fff  libssl.so.0.9.8e  ???
0x2b2f6ade4000 - 0x2b2f6b011fff  libgssapi_krb5.so.2.2  ???
0x2b2f6b012000 - 0x2b2f6b2a6fff  libkrb5.so.3.3  ???
0x2b2f6b2a7000 - 0x2b2f6b4a8fff  libcom_err.so.2.1  ???
0x2b2f6b4a9000 - 0x2b2f6b6cdfff  libk5crypto.so.3.1  ???
0x2b2f6b6ce000 - 0x2b2f6b8d5fff  libkrb5support.so.0.1  ???
0x2b2f6b8d6000 - 0x2b2f6bad7fff  libkeyutils-1.2.so  ???
0x2b2f6bad8000 - 0x2b2f6bceafff  libresolv-2.5.so  ???
0x2b2f6bced000 - 0x2b2f6bf03fff  libselinux.so.1  ???
0x2b2f6bf05000 - 0x2b2f6c140fff  libsepol.so.1  ???
0x7fff2b3bd000 - 0x7fff2b3bffff  linux-gate.so  ???
```

**Comment by Vitallium** [comment]
Please upgrade to PhantomJS 2.0. 1.9.x is no longer supported, and known to have many crasher bugs that are fixed in 2.0.
