### ISSUE TITLE
PhantomJSDriver.quit does not shutdown the process after the driver has successfully run a phantomJS script

### ISSUE THREAD

**Issue by meghana-viswanath** [ariya/phantomjs#13360]
I am on the latest releases of both phantomJS (2.0) and GhostDriver (1.2.0). I am using the driver in my Play/Scala SBT project on OS X Yosmite 10.10.2.

I am basically trying to generate PDFs using phantomJS. I have seen and am able to consistently reproduce a problem where after having successfully run the phantomJS script (similar to rasterize.js example) via the driver, calling the PhantomJSDriver.quit method does not shutdown the phantomJS process. But, the quit method works when I immediately call it after creation without having run any scripts. So, it seems like executing a script using the 'PhantomJSDriver.executePhantomJS' method puts the driver is a state from which it is unable to quit and shutdown the process.

I also tried downgrading my driver to 1.1.0 against phantomJS 2.0 and downgrading phantomJS to 1.9.2 against GhostDriver 1.2.0. No luck.

I have also tried writing the code in pure Java as opposed to Scala and this makes no difference.

Killing the process manually throws up this exception in the app logs -

```
org.openqa.selenium.UnsupportedCommandException: 
Command duration or timeout: 1674.09 seconds
Build info: version: '2.41.0', revision: '3192d8a6c4449dc285928ba024779344f5423c58', time: '2014-03-27 11:29:39'
System info: host: 'MacBook-Pro.local', ip: , os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_25'
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=2.0.0, platform=MAC, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.2.0, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 761c80f0-1a55-11e5-b3c3-f1da1e0b9557
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:610)
    at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:464)
    at business.PdfGenerator$$anonfun$waitForFileGenerationToFinish$1.apply(PdfGenerator.scala:51)
    at business.PdfGenerator$$anonfun$waitForFileGenerationToFinish$1.apply(PdfGenerator.scala:46)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
If needed I can create a test harness and pass it along.

**Comment by meghana-viswanath** [comment]
Found that calling a phantomjs script that uses phantom.exit and then calling PhantomJSDriver.quit messes it up and leaves the process running until explicitly killed.
Closing this off.
