### ISSUE TITLE
2.0 crashes 

### ISSUE THREAD

**Issue by Ivan0626** [ariya/phantomjs#13502]
Hi
I use phantomjs2 hanppens this error:
1   0x1733b97 /opt/phantomjs/bin/phantomjs() [0x1733b97]
2   0x1756558 /opt/phantomjs/bin/phantomjs() [0x1756558]
3   0x175b534 /opt/phantomjs/bin/phantomjs() [0x175b534]
4   0x1588a23 /opt/phantomjs/bin/phantomjs() [0x1588a23]
5   0x1409bc9 /opt/phantomjs/bin/phantomjs() [0x1409bc9]
6   0x13ec4d6 /opt/phantomjs/bin/phantomjs() [0x13ec4d6]
7   0x140057e /opt/phantomjs/bin/phantomjs() [0x140057e]
8   0x1675d76 /opt/phantomjs/bin/phantomjs() [0x1675d76]
9   0x1451da5 /opt/phantomjs/bin/phantomjs() [0x1451da5]
10  0x1455981 /opt/phantomjs/bin/phantomjs() [0x1455981]
11  0x167d675 /opt/phantomjs/bin/phantomjs() [0x167d675]
12  0x1457ab3 /opt/phantomjs/bin/phantomjs() [0x1457ab3]
13  0x201c269 /opt/phantomjs/bin/phantomjs() [0x201c269]
14  0x17a8f9c /opt/phantomjs/bin/phantomjs() [0x17a8f9c]
15  0x17ae85e /opt/phantomjs/bin/phantomjs() [0x17ae85e]
16  0x1ff4d74 /opt/phantomjs/bin/phantomjs() [0x1ff4d74]
17  0x203bc02 /opt/phantomjs/bin/phantomjs() [0x203bc02]
18  0x2039ed0 /opt/phantomjs/bin/phantomjs() [0x2039ed0]
19  0x1b161f5 /opt/phantomjs/bin/phantomjs() [0x1b161f5]
20  0x1ff3fd1 /opt/phantomjs/bin/phantomjs() [0x1ff3fd1]
21  0x1ff66ed /opt/phantomjs/bin/phantomjs() [0x1ff66ed]
22  0x440f71 /opt/phantomjs/bin/phantomjs() [0x440f71]
23  0x3a2a81ed5d /lib64/libc.so.6(__libc_start_main+0xfd) [0x3a2a81ed5d]
24  0x427089 /opt/phantomjs/bin/phantomjs() [0x427089]
PhantomJS has crashed. Please read the crash reporting guide at
http://phantomjs.org/crash-reporting.html and file a bug report at
https://github.com/ariya/phantomjs/issues/new.
Unfortunately, no crash dump is available.
(Is $TMPDIR (/tmp) a directory you cannot write?)
2015-08-17 15:21:44[ERROR] ==> Unable to locate element
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'crawl05', ip: '10.168.26.107', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-431.23.3.el6.x86_64', java.version: '1.7.0_75'
Driver info: driver.version: RemoteWebDriver
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:307)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByClassName(RemoteWebDriver.java:388)
        at org.openqa.selenium.By$ByClassName.findElement(By.java:393)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:299)
        at com.sanyanyu.spider.crawl.CrawlProductByShop2.parseProduct(CrawlProductByShop2.java:189)
        at com.sanyanyu.spider.crawl.CrawlProductByShop2.crawling(CrawlProductByShop2.java:160)
        at com.sanyanyu.spider.crawl.CrawlProductByShop2.main(CrawlProductByShop2.java:44)
Caused by: org.openqa.selenium.WebDriverException: The PhantomJS/GhostDriver server has unexpectedly died!
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'crawl05', ip: '10.168.26.107', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-431.23.3.el6.x86_64', java.version: '1.7.0_75'
Driver info: driver.version: RemoteWebDriver
        at org.openqa.selenium.phantomjs.PhantomJSCommandExecutor.execute(PhantomJSCommandExecutor.java:88)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:527)
        ... 7 more
# Caused by: java.net.ConnectException: Connection refused

/tmp dir's permission:
drwxrwxrwt.   3 root root 12288 Aug 17 15:15 tmp

/opt/phantomjs dir's permission:
drwxr-xr-x  10 root root     4096 Aug 17 13:13 phantomjs

I appreciate your help, Thanks!

**Comment by zackw** [comment]
This is almost certainly a bug in WebKit, and we can't do anything about it without a self-contained test case.  (That *ideally* means a single HTML file that loads no external resources, and has been made as small as possible, but loading it into PhantomJS still triggers the crash.  If you need to have some external resources, that's okay as long as you can bundle everything necessary up in a zipfile that we can unpack into a directory on a webserver and load the HTML.  Server side code is Right Out.)

Your stack trace is, unfortunately, useless, because it doesn't have any function names in it.  (We really ought to deemphasize stack traces in the bug reporting docs -- they tend to be useless even *with* function names, and what we really need is a test case.)

The "Is $TMPDIR a directory you cannot write" message is a red herring.  The crash dumper didn't work, but again, crash dumps tend to be useless...

**Comment by zackw** [comment]
Also, please try to make the crash happen without Selenium, that cuts out a bunch of extra complexity.

**Comment by Ivan0626** [comment]
Thanks @zackw 
Then I use phantomjs 1.9.8 with Selenium to run normal.

**Comment by zackw** [comment]
@Ivan0626 I'm not sure I understand you.  The crash does not happen in 1.9.8?

We still need that test case.

**Comment by Ivan0626** [comment]
@zackw yes, The crash does not happen in 1.9.8, but happen in 2.
Here are my test case:
*****************************phantomjs 2**************************
2015-08-27 20:26:50[INFO] ==> crawl product by shop url start...
Aug 27, 2015 8:26:50 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: /opt/phantomjs/bin/phantomjs
Aug 27, 2015 8:26:50 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 3498
Aug 27, 2015 8:26:50 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--web-security=false, --ssl-protocol=any, --ignore-ssl-errors=true, --webdriver-loglevel=INFO, --load-images=false, --disk-cache=true, --webdriver=3498, --webdriver-logfile=/opt/phantomjsdriver.log]
Aug 27, 2015 8:26:50 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
[INFO  - 2015-08-27T12:26:51.412Z] GhostDriver - Main - running on port 3498
[INFO  - 2015-08-27T12:26:51.796Z] Session [e534f4c0-4cb6-11e5-997c-8f5762c37e85] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":false,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.0.1-development Safari/538.1","webSecurityEnabled":false}
[INFO  - 2015-08-27T12:26:51.797Z] Session [e534f4c0-4cb6-11e5-997c-8f5762c37e85] - page.customHeaders:  - {}
[INFO  - 2015-08-27T12:26:51.798Z] Session [e534f4c0-4cb6-11e5-997c-8f5762c37e85] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.0.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":false,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2015-08-27T12:26:51.798Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: e534f4c0-4cb6-11e5-997c-8f5762c37e85
2015-08-27 20:26:51[INFO] ==> 启动phantomjs耗时：1345ms
2015-08-27 20:26:51[INFO] ==> Selenium downloading page: http://shop34457384.taobao.com
2015-08-27 20:26:52[INFO] ==> 下载店铺[http://shop34457384.taobao.com]页面耗时：569ms
2015-08-27 20:26:53[INFO] ==> total pages :28
2015-08-27 20:26:54[INFO] ==> 下载第[2]页耗时：253ms

*****************************The same below***************content too long****************** 

2015-08-27 20:27:48[INFO] ==> 解析第[28]页耗时：389ms
2015-08-27 20:27:48[INFO] ==> total products :649
2015-08-27 20:27:48[INFO] ==> 解析店铺的所有产品Id总共耗时：56339ms
2015-08-27 20:27:51[INFO] ==> 下载产品[16897735869]页面耗时：2787ms
2015-08-27 20:27:53[INFO] ==> Product [id=null, prdNo=16897735869, prdName=山东电信10元话费充值十元 全国快充秒冲 中国移动10元话费自动充, imgUri=null, brand=, cat=50011814, url=http://detail.taobao.com/item.htm?id=16897735869, price=9.80, monthSale=, paySuccess=null, payRecord=null, comments=, goodNum=null, normalNum=null, badNum=null, sellerAddr=北京, keeperName=null, keeperUrl=null, shopId=null, shopName=玲玲杂货天堂, shopUrl=https://linlinka.taobao.com/, shopParamUrl=null, catchDate=2015-08-27, param=产品名称：山东电信10元
面值: 10元
地区: 山东
充值方式: 卖家代充, skuId=null, skuCode=null, promoType=null, coin=null, coinValue=null, catPath=null, proPrice=null, collectNum=17, suit=null, hasCombo=null, sellerId= 59385116, start=null, end=null]
2015-08-27 20:27:53[INFO] ==> 解析产品[16897735869]页面耗时：1543ms
2015-08-27 20:27:53[INFO] ==> 下载产品[19932716788]页面耗时：533ms
2015-08-27 20:27:56[INFO] ==> Product [id=null, prdNo=19932716788, prdName=官方自动充值 QQ1Q币1个q币 腾讯Q币直充 无需密码 只冲Q币, imgUri=null, brand=, cat=50005462, url=http://detail.taobao.com/item.htm?id=19932716788, price=0.96, monthSale=, paySuccess=null, payRecord=null, comments=, goodNum=null, normalNum=null, badNum=null, sellerAddr=北京, keeperName=null, keeperUrl=null, shopId=null, shopName=玲玲杂货天堂, shopUrl=https://linlinka.taobao.com/, shopParamUrl=null, catchDate=2015-08-27, param=产品名称：QQ币1个直充
充值数量/面值: 1个/按元充
充值类型: 卖家代充
QQ币充值类型: 官方充值, skuId=null, skuCode=null, promoType=null, coin=null, coinValue=null, catPath=null, proPrice=null, collectNum=10, suit=null, hasCombo=null, sellerId= 59385116, start=null, end=null]

*****************************The same below***************content too long****************** 

2015-08-27 20:44:10[INFO] ==> 解析产品[10974038060]页面耗时：2236ms
2015-08-27 20:44:11[INFO] ==> 下载产品[10973771504]页面耗时：816ms
1   0x1733b97 /opt/phantomjs/bin/phantomjs() [0x1733b97]
2   0x1774e95 /opt/phantomjs/bin/phantomjs() [0x1774e95]
3   0x175ca49 /opt/phantomjs/bin/phantomjs() [0x175ca49]
4   0x145b133 /opt/phantomjs/bin/phantomjs() [0x145b133]
5   0x145b489 /opt/phantomjs/bin/phantomjs() [0x145b489]
6   0x13fabcc /opt/phantomjs/bin/phantomjs() [0x13fabcc]
7   0x1676966 /opt/phantomjs/bin/phantomjs() [0x1676966]
8   0x167780c /opt/phantomjs/bin/phantomjs() [0x167780c]
9   0x15aabb6 /opt/phantomjs/bin/phantomjs() [0x15aabb6]
10  0x15b9c94 /opt/phantomjs/bin/phantomjs() [0x15b9c94]
2015-08-27 20:44:14[INFO] ==> I/O exception (org.apache.http.NoHttpResponseException) caught when processing request: The target server failed to respond
2015-08-27 20:44:14[INFO] ==> Retrying request
2015-08-27 20:44:14[ERROR] ==> Unable to locate element
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'crawl05', ip: '10.168.26.107', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-431.23.3.el6.x86_64', java.version: '1.7.0_75'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:152)
	at com.sanyanyu.spider.crawl.CrawlProductByShop2.parseProduct(CrawlProductByShop2.java:208)
	at com.sanyanyu.spider.crawl.CrawlProductByShop2.crawling(CrawlProductByShop2.java:160)
	at com.sanyanyu.spider.crawl.CrawlProductByShop2.main(CrawlProductByShop2.java:44)
Caused by: org.openqa.selenium.WebDriverException: The PhantomJS/GhostDriver server has unexpectedly died!
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'crawl05', ip: '10.168.26.107', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-431.23.3.el6.x86_64', java.version: '1.7.0_75'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.phantomjs.PhantomJSCommandExecutor.execute(PhantomJSCommandExecutor.java:88)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:527)
	... 5 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:178)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:671)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:486)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.HttpCommandExecutor.fallBackExecute(HttpCommandExecutor.java:319)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:298)
	at org.openqa.selenium.phantomjs.PhantomJSCommandExecutor.execute(PhantomJSCommandExecutor.java:82)
	... 6 more
2015-08-27 20:44:14[INFO] ==> Product [id=null, prdNo=10973771504, prdName=电脑自动充值/QQ会员6个月/官方秒充/可查时间/无需密码/可累加, imgUri=null, brand=null, cat=50007212, url=http://detail.taobao.com/item.htm?id=10973771504, price=54.24, monthSale=, paySuccess=null, payRecord=null, comments=, goodNum=null, normalNum=null, badNum=null, sellerAddr=北京, keeperName=null, keeperUrl=null, shopId=null, shopName=null, shopUrl=null, shopParamUrl=null, catchDate=2015-08-27, param=null, skuId=null, skuCode=null, promoType=null, coin=null, coinValue=null, catPath=null, proPrice=null, collectNum=, suit=null, hasCombo=null, sellerId= 59385116, start=null, end=null]
2015-08-27 20:44:14[INFO] ==> 解析产品[10973771504]页面耗时：2702ms
Exception in thread "main" org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'crawl05', ip: '10.168.26.107', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-431.23.3.el6.x86_64', java.version: '1.7.0_75'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:276)
	at com.sanyanyu.spider.crawl.CrawlProductByShop2.crawling(CrawlProductByShop2.java:155)
	at com.sanyanyu.spider.crawl.CrawlProductByShop2.main(CrawlProductByShop2.java:44)
Caused by: org.openqa.selenium.WebDriverException: The PhantomJS/GhostDriver server has unexpectedly died!
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'crawl05', ip: '10.168.26.107', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-431.23.3.el6.x86_64', java.version: '1.7.0_75'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.phantomjs.PhantomJSCommandExecutor.execute(PhantomJSCommandExecutor.java:88)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:527)
	... 3 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:178)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.HttpCommandExecutor.fallBackExecute(HttpCommandExecutor.java:319)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:298)
	at org.openqa.selenium.phantomjs.PhantomJSCommandExecutor.execute(PhantomJSCommandExecutor.java:82)
	... 4 more

*****************************phantomjs 2**************************
*****************************phantomjs 1.9.8**************************
2015-08-27 20:23:54[INFO] ==> crawl product by shop url start...
Aug 27, 2015 8:23:54 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: /opt/phantomjs-1.9.8-linux-x86_64/bin/phantomjs
Aug 27, 2015 8:23:54 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 28900
Aug 27, 2015 8:23:54 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--web-security=false, --ssl-protocol=any, --ignore-ssl-errors=true, --webdriver-loglevel=INFO, --load-images=false, --disk-cache=true, --webdriver=28900, --webdriver-logfile=/opt/phantomjsdriver.log]
Aug 27, 2015 8:23:54 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
PhantomJS is launching GhostDriver...
[INFO  - 2015-08-27T12:23:54.829Z] GhostDriver - Main - running on port 28900
[INFO  - 2015-08-27T12:23:55.354Z] Session [7c0a5940-4cb6-11e5-a2dd-0174802c5f92] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":false,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34","webSecurityEnabled":false}
[INFO  - 2015-08-27T12:23:55.355Z] Session [7c0a5940-4cb6-11e5-a2dd-0174802c5f92] - page.customHeaders:  - {}
[INFO  - 2015-08-27T12:23:55.355Z] Session [7c0a5940-4cb6-11e5-a2dd-0174802c5f92] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"1.9.8","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":false,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2015-08-27T12:23:55.356Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 7c0a5940-4cb6-11e5-a2dd-0174802c5f92
2015-08-27 20:23:55[INFO] ==> 启动phantomjs耗时：1267ms
2015-08-27 20:23:55[INFO] ==> Selenium downloading page: http://shop34457384.taobao.com
2015-08-27 20:23:56[INFO] ==> 下载店铺[http://shop34457384.taobao.com]页面耗时：785ms
2015-08-27 20:23:56[INFO] ==> total pages :28
2015-08-27 20:23:58[INFO] ==> 下载第[2]页耗时：308ms

*****************************The same below***************content too long****************** 

2015-08-27 20:24:57[INFO] ==> 解析第[28]页耗时：579ms
2015-08-27 20:24:57[INFO] ==> total products :649
2015-08-27 20:24:57[INFO] ==> 解析店铺的所有产品Id总共耗时：61156ms
2015-08-27 20:25:01[INFO] ==> 下载产品[16897735869]页面耗时：3999ms
2015-08-27 20:25:02[INFO] ==> Product [id=null, prdNo=16897735869, prdName=山东电信10元话费充值十元 全国快充秒冲 中国移动10元话费自动充, imgUri=null, brand=, cat=50011814, url=http://detail.taobao.com/item.htm?id=16897735869, price=9.80, monthSale=, paySuccess=null, payRecord=null, comments=, goodNum=null, normalNum=null, badNum=null, sellerAddr=北京, keeperName=null, keeperUrl=null, shopId=null, shopName=玲玲杂货天堂, shopUrl=https://linlinka.taobao.com/, shopParamUrl=null, catchDate=2015-08-27, param=产品名称：山东电信10元
面值: 10元
地区: 山东
充值方式: 卖家代充, skuId=null, skuCode=null, promoType=null, coin=null, coinValue=null, catPath=null, proPrice=null, collectNum=17, suit=null, hasCombo=null, sellerId= 59385116, start=null, end=null]

*****************************The same below***************content too long****************** 

2015-08-27 20:57:12[INFO] ==> 解析产品[10469861160]页面耗时：2367ms
2015-08-27 20:57:12[INFO] ==> 下载产品[41159017167]页面耗时：691ms
2015-08-27 20:57:14[INFO] ==> Product [id=null, prdNo=41159017167, prdName=河北移动20元快充值交话费石家庄唐山邯郸廊坊衡水保定自动冲值秒, imgUri=null, brand=, cat=150401, url=http://detail.taobao.com/item.htm?id=41159017167, price=20.05, monthSale=, paySuccess=null, payRecord=null, comments=, goodNum=null, normalNum=null, badNum=null, sellerAddr=北京, keeperName=null, keeperUrl=null, shopId=null, shopName=玲玲杂货天堂, shopUrl=https://linlinka.taobao.com/, shopParamUrl=null, catchDate=2015-08-27, param=产品名称：河北移动20元
面值: 20元
地区: 河北
充值方式: 卖家代充, skuId=null, skuCode=null, promoType=null, coin=null, coinValue=null, catPath=null, proPrice=null, collectNum=, suit=null, hasCombo=null, sellerId= 59385116, start=null, end=null]
2015-08-27 20:57:14[INFO] ==> 解析产品[41159017167]页面耗时：2031ms
2015-08-27 20:57:14[INFO] ==> crawl product by shop url end！！！
2015-08-27 20:57:14[INFO] ==> Quit webDriver PhantomJSDriver: phantomjs on LINUX (7c0a5940-4cb6-11e5-a2dd-0174802c5f92)
[INFO  - 2015-08-27T12:57:15.071Z] ShutdownReqHand - _handle - About to shutdown

*****************************phantomjs 1.9.8**************************

**Comment by zackw** [comment]
> @zackw yes, The crash does not happen in 1.9.8, but happen in 2.

Thank you.

> Here are my test case:

I'm sorry, that's not a test case.  I understand from this log that you are using PhantomJS in WebDriver mode to crawl taobao.com, and I even see some specific URLs in there, but if I try to do the same thing there is no guarantee that I will get the same result, because taobao is changing all the time and may send different content to people in different locations.

A test case for us is a self-contained HTML file plus a PhantomJS controller script.  Please see https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases for more explanation of what this should be like.
