### ISSUE TITLE
[2.0] Fonts rendering causes browser crash

### ISSUE THREAD

**Issue by Palid** [ariya/phantomjs#13589]
PhantomJS 2.0 crashes when used to screencap website `pagepro.pl`

Attaching stacktrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000001c3b548 in QFontconfigDatabase::fontEngine(QByteArray const&, double, QFont::HintingPreference) ()

(gdb) bt
#0  0x0000000001c3b548 in QFontconfigDatabase::fontEngine(QByteArray const&, double, QFont::HintingPreference) ()
#1  0x0000000001dda88a in QRawFontPrivate::platformLoadFromData(QByteArray const&, double, QFont::HintingPreference) ()
#2  0x0000000000875df4 in WebCore::createFontCustomPlatformData(WebCore::SharedBuffer*) ()
#3  0x000000000061df16 in WebCore::CachedFont::ensureCustomFontData() ()
#4  0x00000000013af0dc in WebCore::CSSFontFaceSource::getFontData(WebCore::FontDescription const&, bool, bool, WebCore::CSSFontSelector*) ()
#5  0x00000000013af543 in WebCore::CSSFontFace::getFontData(WebCore::FontDescription const&, bool, bool) ()
#6  0x00000000013b85bb in WebCore::CSSSegmentedFontFace::getFontData(WebCore::FontDescription const&) ()
#7  0x00000000013e69b1 in WebCore::CSSFontSelector::getFontData(WebCore::FontDescription const&, WTF::AtomicString const&) ()
#8  0x000000000073ae2e in WebCore::FontCache::getFontData(WebCore::FontDescription const&, int&, WebCore::FontSelector*) ()
#9  0x000000000072741b in WebCore::FontGlyphs::realizeFontDataAt(WebCore::FontDescription const&, unsigned int) const ()
#10 0x0000000001108a96 in WebCore::RenderStyle::computedLineHeight(WebCore::RenderView*) const ()
#11 0x000000000126a57c in WebCore::RenderBlock::lineHeight(bool, WebCore::LineDirectionMode, WebCore::LinePositionMode) const ()
```

**Comment by zackw** [comment]
Sorry for the delay getting back to you about this.

This does not crash for me:

    ./bin/phantomjs examples/rasterize.js http://pagepro.pl/ /tmp/test.png

Based on the backtrace, I suspect a problem with your font library.  Please make sure you have up-to-date versions of libfreetype and libfontconfig.
