### ISSUE TITLE
phantomjs-1.9.8-windows.zip cannot be downloaded

### ISSUE THREAD

**Issue by jochenvanwylick** [ariya/phantomjs#13676]
Hi - my grunt-mocha is trying to install phantomjs and I'm getting the following error:

````
> phantomjs@1.9.18 install C:\_CODE\...\...\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\Jochen\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...

Error making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:837:11)
    at TLSWrap.onread (net.js:544:26)

Please report this full log at https://github.com/Medium/phantomjs
npm ERR! Windows_NT 10.0.10565
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.0.0
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.18 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.18 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\_CODE\...\...\npm-debug.log
````

I checked the URL: `https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip` and indeed - there's nothing there. Can you please put a file at that location so that the install script can find it again? Thanks.

Dependency chain seems to be the following `grunt-mocha 0.4.13` > `grunt-lib-phantomjs 0.6.0` > `phantomjs 1.9.15`

**Comment by Vitallium** [comment]
Bitbucket is experiencing problems right now - http://status.bitbucket.org/. We can't do nothing with it.
