### ISSUE TITLE
linux on system z support

### ISSUE THREAD

**Issue by elkorep** [ariya/phantomjs#13716]
I was having issues using phantomJS with linux on system z. Does it not support system Z (SUSE 11 and SLES 11) at all?

The tests we have work fine on other machines but come up with errors on linux on system Z SUSE 11 and SLES 11

running our tests with phantomJS I get:

ERROR: /home/nodebot/jnksws/workspace/angular-live-set/arch/s390x/os/sles-11/node_modules/phantomjs/lib/phantom/bin/phantomjs: /home/nodebot/jnksws/workspace/angular-live-set/arch/s390x/os/sles-11/node_modules/phantomjs/lib/phantom/bin/phantomjs: cannot execute binary file

DEBUG: Process PhantomJS exited with code 126
ERROR: Cannot start PhantomJS

I installed phantom js and ran the tests it is packaged with using npm test and got this error:

> phantomjs@1.9.18 test /home/nodebot1/elkorep/node_modules/phantomjs
> nodeunit --reporter=minimal test/tests.js

tests.js: .FFF.
AssertionError: Test script should have executed and returned run time
    at Object.ok (/home/nodebot1/elkorep/node_modules/phantomjs/node_modules/nod                                         eunit/lib/types.js:83:39)
    at /home/nodebot1/elkorep/node_modules/phantomjs/test/tests.js:29:10
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

AssertionError: 126 == 123
    at Object.equals (/home/nodebot1/elkorep/node_modules/phantomjs/node_modules                                         /nodeunit/lib/types.js:83:39)
    at /home/nodebot1/elkorep/node_modules/phantomjs/test/tests.js:38:10
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

AssertionError: Version should be match
    at Object.equal (/home/nodebot1/elkorep/node_modules/phantomjs/node_modules/                                         nodeunit/lib/types.js:83:39)
    at /home/nodebot1/elkorep/node_modules/phantomjs/test/tests.js:52:10
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

FAILURES: 3/9 assertions failed (137ms)
TAP version 13
1..0
# time=155.588ms
npm ERR! Test failed.  See above for more details.

**Comment by Vitallium** [comment]
Exit code 126 means that you don't have permission to execute the binary itself (probably something wrong with your setup).
Try to reinstall the package.

I'm closing the issue, because this is not the PhantomJS issue. See also here #11646
