### ISSUE TITLE
Phantomjs crash: QFontconfigDatabase::fontEngine

### ISSUE THREAD

**Issue by Vanuan** [ariya/phantomjs#13853]
Having a crash when using manually built 2.0.0 on CentOS 6. Full stacktrace: 
```
Core was generated by `/opt/phantomjs/2.0.0/bin/phantomjs --local-storage-path=/data/6fa5b5a8-fa67-495'.
#0  0x0000000001b14c99 in QFontconfigDatabase::fontEngine(QByteArray const&, double, QFont::HintingPreference) ()
(gdb) bt
#0  0x0000000001b14c99 in QFontconfigDatabase::fontEngine(QByteArray const&, double, QFont::HintingPreference) ()
#1  0x0000000001ca5535 in QRawFontPrivate::platformLoadFromData(QByteArray const&, double, QFont::HintingPreference) ()
#2  0x0000000000889d79 in WebCore::createFontCustomPlatformData(WebCore::SharedBuffer*) ()
#3  0x0000000000617bd6 in WebCore::CachedFont::ensureCustomFontData() ()
#4  0x0000000001201d45 in WebCore::CSSFontFaceSource::getFontData(WebCore::FontDescription const&, bool, bool, WebCore::CSSFontSelector*) ()
#5  0x0000000001202100 in WebCore::CSSFontFace::getFontData(WebCore::FontDescription const&, bool, bool) ()
#6  0x0000000001202396 in WebCore::CSSSegmentedFontFace::getFontData(WebCore::FontDescription const&) ()
#7  0x0000000001282b31 in WebCore::CSSFontSelector::getFontData(WebCore::FontDescription const&, WTF::AtomicString const&) ()
#8  0x0000000000743ab1 in WebCore::FontCache::getFontData(WebCore::FontDescription const&, int&, WebCore::FontSelector*) ()
#9  0x000000000072e658 in WebCore::FontGlyphs::realizeFontDataAt(WebCore::FontDescription const&, unsigned int) const ()
#10 0x000000000111de8a in WebCore::TextRun WebCore::constructTextRunInternal<unsigned short>(WebCore::RenderObject*, WebCore::Font const&, unsigned short const*, int, WebCore::RenderStyle*, unsigned int) ()
#11 0x000000000116a09a in WebCore::RenderText::computePreferredLogicalWidths(float, WTF::HashSet<WebCore::SimpleFontData const*, WTF::PtrHash<WebCore::SimpleFontData const*>, WTF::HashTraits<WebCore::SimpleFontData const*> >&, WebCore::GlyphOverflow&) ()
#12 0x000000000116b462 in WebCore::RenderText::computePreferredLogicalWidths(float) ()
#13 0x000000000114a532 in WebCore::RenderText::trimmedPrefWidths(float, float&, bool&, float&, bool&, bool&, bool&, float&, float&, float&, float&, bool&) ()
#14 0x000000000114b0a0 in WebCore::RenderBlock::computeInlinePreferredLogicalWidths(WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#15 0x000000000114c39d in WebCore::RenderBlock::computeIntrinsicLogicalWidths(WebCore::LayoutUnit&, WebCore::LayoutUnit&) const ()
#16 0x00000000011165f5 in WebCore::RenderBlock::computePreferredLogicalWidths()
    ()
#17 0x0000000001156d12 in WebCore::RenderTableCell::computePreferredLogicalWidths() ()
#18 0x0000000001085363 in WebCore::RenderBox::minPreferredLogicalWidth() const
    ()
#19 0x0000000001146b66 in WebCore::AutoTableLayout::recalcColumn(unsigned int)
    ()
#20 0x000000000114778f in WebCore::AutoTableLayout::fullRecalc() ()
#21 0x0000000001149ba5 in WebCore::AutoTableLayout::computeIntrinsicLogicalWidths(WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#22 0x00000000011067ce in WebCore::RenderTable::computePreferredLogicalWidths()

#23 0x0000000001085363 in WebCore::RenderBox::minPreferredLogicalWidth() const
    ()
#24 0x0000000001190840 in WebCore::RenderTable::updateLogicalWidth() ()
#25 0x00000000011b35b4 in WebCore::RenderTable::layout() ()
#26 0x000000000118e58a in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#27 0x0000000001191e0d in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#28 0x00000000011c71d3 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#29 0x00000000010b471e in WebCore::RenderBlock::layout() ()
#30 0x000000000118e58a in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#31 0x0000000001191e0d in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#32 0x00000000011c71d3 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#33 0x00000000010b471e in WebCore::RenderBlock::layout() ()
#34 0x000000000118e58a in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#35 0x0000000001191e0d in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#36 0x00000000011c71d3 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#37 0x00000000010b471e in WebCore::RenderBlock::layout() ()
#38 0x00000000007eca85 in WebCore::RenderFlexibleBox::layoutAndPlaceChildren(WebCore::LayoutUnit&, WTF::Vector<WebCore::RenderBox*, 0ul, WTF::CrashOnOverflow> const&, WTF::Vector<WebCore::LayoutUnit, 0ul, WTF::CrashOnOverflow> const&, WebCore::LayoutUnit, bool, WTF::Vector<WebCore::RenderFlexibleBox::LineContext, 0ul, WTF::CrashOnOverflow>&) ()
#39 0x00000000007ecfdd in WebCore::RenderFlexibleBox::layoutFlexItems(bool, WTF::Vector<WebCore::RenderFlexibleBox::LineContext, 0ul, WTF::CrashOnOverflow>&)
    ()
#40 0x00000000007ee5e2 in WebCore::RenderFlexibleBox::layoutBlock(bool, WebCore::LayoutUnit) ()
#41 0x00000000010b471e in WebCore::RenderBlock::layout() ()
#42 0x00000000007ea8d8 in WebCore::RenderFlexibleBox::preferredMainAxisContentExtentForChild(WebCore::RenderBox*, bool) ()
#43 0x00000000007eb39e in WebCore::RenderFlexibleBox::computeNextFlexLine(WTF::Vector<WebCore::RenderBox*, 0ul, WTF::CrashOnOverflow>&, WebCore::LayoutUnit&, double&, double&, WebCore::LayoutUnit&, bool&) ()
#44 0x00000000007ecef6 in WebCore::RenderFlexibleBox::layoutFlexItems(bool, WTF::Vector<WebCore::RenderFlexibleBox::LineContext, 0ul, WTF::CrashOnOverflow>&)
    ()
#45 0x00000000007ee5e2 in WebCore::RenderFlexibleBox::layoutBlock(bool, WebCore::LayoutUnit) ()
#46 0x00000000010b471e in WebCore::RenderBlock::layout() ()
#47 0x00000000007ea8d8 in WebCore::RenderFlexibleBox::preferredMainAxisContentExtentForChild(WebCore::RenderBox*, bool) ()
#48 0x00000000007eb39e in WebCore::RenderFlexibleBox::computeNextFlexLine(WTF::Vector<WebCore::RenderBox*, 0ul, WTF::CrashOnOverflow>&, WebCore::LayoutUnit&, double&, double&, WebCore::LayoutUnit&, bool&) ()
#49 0x00000000007ecef6 in WebCore::RenderFlexibleBox::layoutFlexItems(bool, WTF::Vector<WebCore::RenderFlexibleBox::LineContext, 0ul, WTF::CrashOnOverflow>&)
    ()
#50 0x00000000007ee5e2 in WebCore::RenderFlexibleBox::layoutBlock(bool, WebCore::LayoutUnit) ()
#50 0x00000000007ee5e2 in WebCore::RenderFlexibleBox::layoutBlock(bool, WebCore::LayoutUnit) ()
#51 0x00000000010b471e in WebCore::RenderBlock::layout() ()
#52 0x00000000010bf931 in WebCore::layoutChildIfNeededApplyingDelta(WebCore::RenderBox*, WebCore::LayoutSize const&) ()
#53 0x0000000001186bdb in WebCore::RenderDeprecatedFlexibleBox::layoutVerticalBox(bool) ()
#54 0x00000000011b221c in WebCore::RenderDeprecatedFlexibleBox::layoutBlock(bool, WebCore::LayoutUnit) ()
#55 0x00000000010b471e in WebCore::RenderBlock::layout() ()
#56 0x000000000118e58a in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#57 0x0000000001191e0d in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#58 0x00000000011c71d3 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#59 0x00000000010b471e in WebCore::RenderBlock::layout() ()
#60 0x000000000118e58a in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#61 0x0000000001191e0d in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#62 0x00000000011c71d3 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#63 0x00000000010b471e in WebCore::RenderBlock::layout() ()
#64 0x000000000118e58a in WebCore::RenderBlock::layoutBlockChild(WebCore::RenderBox*, WebCore::RenderBlock::MarginInfo&, WebCore::LayoutUnit&, WebCore::LayoutUnit&) ()
#65 0x0000000001191e0d in WebCore::RenderBlock::layoutBlockChildren(bool, WebCore::LayoutUnit&) ()
#66 0x00000000011c71d3 in WebCore::RenderBlock::layoutBlock(bool, WebCore::LayoutUnit) ()
#67 0x00000000010b471e in WebCore::RenderBlock::layout() ()
#68 0x00000000010b9ef9 in WebCore::RenderView::layoutContent(WebCore::LayoutState const&) ()
#69 0x00000000011af86a in WebCore::RenderView::layout() ()
#70 0x00000000006f474d in WebCore::FrameView::layout(bool) ()
#71 0x00000000007d7f9b in WebCore::ThreadTimers::sharedTimerFiredInternal() ()
#72 0x000000000201c319 in QObject::event(QEvent*) ()
#73 0x00000000017a904c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
#74 0x00000000017ae90e in QApplication::notify(QObject*, QEvent*) ()
#75 0x0000000001ff4e24 in QCoreApplication::notifyInternal(QObject*, QEvent*)
    ()
#76 0x000000000203bcb2 in QTimerInfoList::activateTimers() ()
#77 0x0000000002039f80 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#78 0x0000000001b162a5 in QUnixEventDispatcherQPA::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#79 0x0000000001ff4081 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#80 0x0000000001ff679d in QCoreApplication::exec() ()
#81 0x0000000000440f61 in main ()
```

**Comment by Vanuan** [comment]
Looks similar to #13090

**Comment by Vanuan** [comment]
Yeap, exactly the same issue. Closing.
