### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by YataoZhang** [ariya/phantomjs#14217]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --2.1.7`.

2. What steps will reproduce the problem?
```js
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-macosx.zip
Saving to /var/folders/26/fk34yzmj2nqfmbwr3_0y90kr0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT 54.231.14.249:443
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
```
3. Which operating system are you using?
macOS
4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.
```js
npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

```

**Comment by Vitallium** [comment]
Thank you for submitting the ticket. But we don't maintain the NPM package. Please file your issue under the corresponding repository. Thank you!
