### ISSUE TITLE
Invalid Command Method - while switching to parent frame

### ISSUE THREAD

**Issue by selvagsz** [ariya/phantomjs#14419]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
   1. Using webdriverio for e2e tests. [`browser.frameParent()`](http://webdriver.io/api/protocol/frameParent.html) throws `Invalid Command Method`
3. Which operating system are you using?
   OS X 10.11.4
4. Did you use binary PhantomJS or did you compile it from source?
   binary
5. Please provide any additional information below.

<details>
<summary>

Log Trace</summary>

```
19:17:40.964 INFO - Executing: [switch to parent frame])
[ERROR - 2016-07-21T13:47:40.968Z] RouterReqHand - _handle.error - {"name":"Invalid Command Method","message":"{\"headers\":{\"Accept-Encoding\":\"gzip,deflate\",\"Connection\":\"Keep-Alive\",\"Content-Length\":\"2\",\"Content-Type\":\"application/json; charset=utf-8\",\"Host\":\"localhost:10643\",\"User-Agent\":\"Apache-HttpClient/4.5.1 (Java/1.8.0_92)\"},\"httpVersion\":\"1.1\",\"method\":\"POST\",\"post\":\"{}\",\"url\":\"/frame/parent\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"parent\",\"directory\":\"/frame/\",\"path\":\"/frame/parent\",\"relative\":\"/frame/parent\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/frame/parent\",\"queryKey\":{},\"chunks\":[\"frame\",\"parent\"]},\"urlOriginal\":\"/session/b125a4e0-4f49-11e6-a714-c1f31aaa0839/frame/parent\"}","line":202,"sourceURL":"phantomjs://code/session_request_handler.js","stack":"_handle@phantomjs://code/session_request_handler.js:202:66\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/router_request_handler.js:78:46"}

  phantomjs://platform/console++.js:263 in error
19:17:40.971 WARN - Exception thrown
org.openqa.selenium.UnsupportedCommandException: Invalid Command Method - {"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"2","Content-Type":"application/json; charset=utf-8","Host":"localhost:10643","User-Agent":"Apache-HttpClient/4.5.1 (Java/1.8.0_92)"},"httpVersion":"1.1","method":"POST","post":"{}","url":"/frame/parent","urlParsed":{"anchor":"","query":"","file":"parent","directory":"/frame/","path":"/frame/parent","relative":"/frame/parent","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/frame/parent","queryKey":{},"chunks":["frame","parent"]},"urlOriginal":"/session/b125a4e0-4f49-11e6-a714-c1f31aaa0839/frame/parent"}
Command duration or timeout: 5 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'Selvas-MacBook-Pro.local', ip: '192.168.0.23', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_92'
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=2.1.1, platform=OS X 10.11, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.2.0, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: b125a4e0-4f49-11e6-a714-c1f31aaa0839
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701)
    at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.parentFrame(RemoteWebDriver.java:1009)
    at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringTargetLocator.parentFrame(EventFiringWebDriver.java:599)
    at org.openqa.selenium.remote.server.handler.SwitchToParentFrame.call(SwitchToParentFrame.java:33)
    at org.openqa.selenium.remote.server.handler.SwitchToParentFrame.call(SwitchToParentFrame.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

</details>

**Comment by jenssvensson** [comment]
+1

Having the same issue.

**Comment by dmaziar** [comment]
I used browser.frame(); as a workaround. It switches to main content if no id is set.

**Comment by jesg** [comment]
this was fixed in ghostdriver a while back.  see detro/ghostdriver@b6b1713f6ff79cd35a870872dc6943978f2f14fc
