### ISSUE TITLE
Phantom js is crashing in my node.js application

### ISSUE THREAD

**Issue by armsofter** [ariya/phantomjs#14427]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
   2.1.1
2. What steps will reproduce the problem?
  1. I just trying to create the pdf from the page.
  2. The same project is working on some other pc in windows 10 but not working on my debian VPS

3. Which operating system are you using?
 Debina on vps

4. Did you use binary PhantomJS or did you compile it from source?

I have compiled from source.

5. Please provide any additional information below.

I have tryed to  remove and install again and again (the global npm, local npm the whole phantomjs but nothing).

I am getting this error on my console when running my app with 'node www' commant. And when calling the command with phantomjs I am getting this error.

error: Could not spawn [/srv/myapp/node_modules/phantom/node_modules/phantomjs-prebuilt/lib/phantom\bin\phantomjs.exe] executable. Please make sure phantomjs is installed correctly.
error:  Error: spawn /srv/myapp/node_modules/phantom/node_modules/phantomjs-prebuilt/lib/phantom\bin\phantomjs.exe ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

**Comment by armsofter** [comment]
Done. Solved. just done npm install phantom --save
