### ISSUE TITLE
phantomjs hangs while opening the url using selenium?

### ISSUE THREAD

**Issue by viveksrinivasanss** [ariya/phantomjs#14621]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.

phantomjs version - 1.9.7 and also in 2.1.1
2. What steps will reproduce the problem?

```
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

dcap = dict(DesiredCapabilities.PHANTOMJS)
dcap["phantomjs.page.settings.userAgent"] = ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/28.0.1500.71 Chrome/28.0.1500.71 Safari/537.36')
driver = webdriver.PhantomJS("/usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs",service_args=['--ignore-ssl-errors=true','--ssl-protocol=any'],desired_capabilities=dcap)
driver.get("https://www.walmart.com/ip/Enfamil-Newborn-Formula-Powder-33.2-oz-Refill-Box/16940597")

print driver.current_url
driver.close()
```

3. Which operating system are you using?

ubuntu 14.04
4. Did you use binary PhantomJS or did you compile it from source?

Binary
5. Please provide any additional information below.

But the similar code works  fine in windows .I have problem only in ubuntu.
I am new to these github things. Kindly tell me if any other details needed.

**Comment by jesg** [comment]
@viveksrinivasanss `yes` is not a valid option for `--ignore-ssl-errors`.  should be `true` or `false`.

```
--ignore-ssl-errors=<val>            Ignores SSL errors (expired/self-signed certificate errors): 'true' or 'false' (default)
```

**Comment by viveksrinivasanss** [comment]
yeah I tried `true` as well. Its not working...Is there any other thing I should take care of....can someone replicate the issue?

**Comment by jesg** [comment]
@viveksrinivasanss both the [npm](https://www.npmjs.com/package/phantomjs-prebuilt) package and [official](http://phantomjs.org/download.html) download works for me on 64bit ubuntu 16. the official ubuntu package looks broken.

package details
```
$ apt-cache show phantomjs
Package: phantomjs
Priority: extra
Section: universe/web
Installed-Size: 919
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Dmitry Smirnov <onlyjob@debian.org>
Architecture: amd64
Version: 2.1.1+dfsg-1
Depends: libc6 (>= 2.15), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.5.0), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5network5 (>= 5.3.0), libqt5printsupport5 (>= 5.0.2), libqt5webkit5 (>= 5.2.0), libqt5widgets5 (>= 5.0.2), libstdc++6 (>= 4.4.0)
Filename: pool/universe/p/phantomjs/phantomjs_2.1.1+dfsg-1_amd64.deb
Size: 307358
MD5sum: ad67963b0d5e870854125d18c4d33e65
SHA1: 0f5302f161c72c2ce47059b59edb1b13d1c0973a
SHA256: 231199593b127eb1000a44f7e0efc6cf26269dcb3aa0c08f6673a657faffc421
Description-en: minimalistic headless WebKit-based with JavaScript API
 PhantomJS is a headless WebKit with JavaScript API. It has fast and native
 support for various web standards: DOM handling, CSS selector, JSON, Canvas,
 and SVG.
 .
 PhantomJS is an optimal solution for headless testing of web-based
 applications, site scraping, pages capture, SVG renderer, PDF converter
 and many other use cases.
Description-md5: bf355eb2a4481e2b6c41bfbf308d318e
Homepage: http://www.phantomjs.org/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
```

i get the following error when i execute your script with the official ubuntu binary
```
Traceback (most recent call last):
  File "/home/jesg/sel-url-test.py", line 10, in <module>
    print driver.current_url
  File "/home/jesg/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 486, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "/home/jesg/.local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 233, in execute
    self.error_handler.check_response(response)
  File "/home/jesg/.local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 165, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: Error - Unable to load Atom 'execute_script' from file ':/ghostdriver/./third_party/webdriver-atoms/execute_script.js'
```
so it looks like the official ubuntu package is broken.  is this the error you are seeing?

**Comment by viveksrinivasanss** [comment]
i dont get any error...it just hangs while it tries to load the url.....hangs forever.......
I used the phantomjs for linux  64 bit from the following link
http://phantomjs.org/download.html

I hope its the correct link to follow.

**Comment by roxma** [comment]
Same issue here

**Comment by roxma** [comment]
Looks like there's a similar issue [here](https://github.com/ariya/phantomjs/issues/14621)

**Comment by essandess** [comment]
The `current_url` method always crashes on GitHub.com. Here's the SSCCE:

```
$ phantomjs --version
2.0.0
$ python3 -c 'from selenium import webdriver; driver = webdriver.PhantomJS(); driver.get("https://github.com"); print(driver.title); print(driver.current_url); driver.quit()'
The world's leading software development platform · GitHub
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 493, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in execute
    self.error_handler.check_response(response)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: {"errorMessage":"Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: \"script-src assets-cdn.github.com\".\n","request":{"objectName":"","statusCode":200,"headers":{"Cache":"no-cache","Content-Type":"application/json;charset=UTF-8"}}}
Screenshot: available via screen
```

**Comment by jesg** [comment]
@essandess the issue you are experiencing should be fixed in ghostdriver 2.0.0.

**Comment by essandess** [comment]
`phantomjs --version` says 2.0.0, and this is with the embedded ghostdriver on a native compile.

**Comment by jesg** [comment]
@essandess phantomjs 2.0.0 embeds ghostdriver 1.2.0 which has issues with sites that have csp (content security policies).

https://github.com/ariya/phantomjs/blob/2.0.0/src/ghostdriver/lastupdate
