### ISSUE TITLE
UnreachableBrowserException occurs after a period of time

### ISSUE THREAD

**Issue by fickmj** [ariya/phantomjs#14997]
1. I am running version 2.1 of the phantomjs driver
2. What steps will reproduce the problem?
 I have a script uses the phantomjs driver to open a website, login, and check a couple pages before logging out.  This script is run on a schedule from within LogicMonitor.  The script runs successfully for many times and then after a period of successful runs starts to fail.  Once failures occur it does not run successfully again without a restart of logicmonitor.  The driver fails to initialize with the following error 
ERROR - org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

3. Which operating system are you using?
Window Server 2012r2

4. Did you use binary PhantomJS or did you compile it from source?  
I used the binary

5. Please provide any additional information below.

**Comment by fickmj** [comment]
I have an update.  The driver actually has the failure shown here and then after that subsequent tries to create a new driver fail until a restart is done.   What could cause this exception to randomly occur and then prevent and new instances from working?

[2017-05-19 12:52:34,819] INFO  - With exception:
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'GeniusMonitor', ip: '192.168.1.32', os.name: 'Windows Server 2012 R2', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_112'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=2.1.1, platform=XP, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.2.0, phantomjs.page.settings.userAgent=Mozilla/5.0 (Macintosh Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 8e9966c0-3cb3-11e7-a823-03f9247cfd7b
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.gsi.genius.jde.app.Datasource$_createGlow_closure1$_closure12$_closure42$_closure45.doCall(Datasource.groovy:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:229)
	at org.codehaus.groovy.runtime.dgm$615.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:248)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.gsi.genius.jde.app.Datasource$_createGlow_closure1$_closure12$_closure42.doCall(Datasource.groovy:133)
	at com.gsi.genius.jde.app.Datasource$_createGlow_closure1$_closure12$_closure42.doCall(Datasource.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.aklein.glow.Step.runClosure(Step.groovy:213)
	at sun.reflect.GeneratedMethodAccessor4148.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:361)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.aklein.glow.Step$_call_closure1.doCall(Step.groovy:78)
	at sun.reflect.GeneratedMethodAccessor4147.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1373)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1366)
	at org.codehaus.groovy.runtime.dgm$149.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.aklein.glow.Step.call(Step.groovy:77)
	at sun.reflect.GeneratedMethodAccessor4168.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.aklein.glow.Glow.call(Glow.groovy:87)
	at org.aklein.glow.Glow$call$4.call(Unknown Source)
	at org.aklein.glow.Step.call(Step.groovy:83)
	at sun.reflect.GeneratedMethodAccessor4168.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.aklein.glow.Glow.call(Glow.groovy:87)
	at org.aklein.glow.Glow$call$4.call(Unknown Source)
	at org.aklein.glow.Step.call(Step.groovy:83)
	at sun.reflect.GeneratedMethodAccessor4168.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.aklein.glow.Glow.call(Glow.groovy:87)
	at org.aklein.glow.Glow$call$4.call(Unknown Source)
	at org.aklein.glow.Step.call(Step.groovy:83)
	at sun.reflect.GeneratedMethodAccessor4168.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.aklein.glow.Glow.call(Glow.groovy:87)
	at org.aklein.glow.Glow$call$4.call(Unknown Source)
	at org.aklein.glow.Step.call(Step.groovy:83)
	at sun.reflect.GeneratedMethodAccessor4168.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.aklein.glow.Glow.call(Glow.groovy:87)
	at org.aklein.glow.Glow$call$4.call(Unknown Source)
	at org.aklein.glow.Step.call(Step.groovy:83)
	at sun.reflect.GeneratedMethodAccessor4168.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.aklein.glow.Glow.call(Glow.groovy:87)
	at org.aklein.glow.Glow$call$4.call(Unknown Source)
	at org.aklein.glow.Step.call(Step.groovy:83)
	at sun.reflect.GeneratedMethodAccessor4168.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.aklein.glow.Glow.call(Glow.groovy:87)
	at org.aklein.glow.Glow$call$4.call(Unknown Source)
	at org.aklein.glow.Step.call(Step.groovy:83)
	at sun.reflect.GeneratedMethodAccessor4168.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.aklein.glow.Glow.call(Glow.groovy:87)
	at org.aklein.glow.Glow$call$4.call(Unknown Source)
	at org.aklein.glow.Step.call(Step.groovy:83)
	at sun.reflect.GeneratedMethodAccessor4168.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at org.aklein.glow.Glow.start(Glow.groovy:54)
	at org.aklein.glow.Glow$start$1.call(Unknown Source)
	at com.gsi.genius.core.DatasourceBase.run(DatasourceBase.groovy:33)
	at com.gsi.genius.core.DatasourceBase$run$0.call(Unknown Source)
	at Script17.run(Script17.groovy:7)
	at com.santaba.agent.util.GroovyScriptShell.execute(GroovyScriptShell.java:131)
	at com.santaba.agent.util.GroovyScriptExecutor.execute(GroovyScriptExecutor.java:121)
	at com.santaba.agent.collector3.script.ScriptTask._collect(ScriptTask.java:264)
	at com.santaba.agent.collector3.DataCollectingTask.execute(DataCollectingTask.java:123)
	at com.santaba.agent.collector3.CollectingTaskExecutionRunable.run(CollectingTaskExecutionRunable.java:20)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset

**Comment by kensoh** [comment]
Hi @fickmj I'm a CasperJS user for couple of years, now browsing through open issues on CasperJS/PhantomJS. It sounds like you are driving PhantomJS through Ghost Driver through Selenium? You might want to raise an issue with Ghost Driver repo to see if they can help. https://github.com/detro/ghostdriver

Also, is it possible from LogicMonitor to re-initialize your testing framework of Selenium + any other relevant tools from time to time after certain number of executions? So that any memory related issues are isolated from the root cause.

**Comment by fickmj** [comment]
Ken,

Thank you for your response.  I will investigate posting to the ghostdriver issues also.  This is code I’ve inherited and I won’t pretend that I understand how this driver functions under the covers.  It is using the latest phantomjs driver version 2.1.1
We are using the following capabilities [{phantomjs.page.settings.userAgent=Mozilla/5.0 (Macintosh Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36, browserName=phantomjs, phantomjs.cli.args=[Ljava.lang.String;@76d09215, version=, platform=ANY}]

We are setting these browser args
JdeBrowser - Adding to browser args : --web-security=false
[2017-05-19 12:52:33,093] INFO  - JdeBrowser - Adding to browser args : --ssl-protocol=any
[2017-05-19 12:52:33,093] INFO  - JdeBrowser - Adding to browser args : --ignore-ssl-errors=true
[2017-05-19 12:52:33,093] INFO  - JdeBrowser - Adding to browser args : --webdriver-logfile=C:\Program Files (x86)\LogicMonitor\Agent\gsi\genius\dslogs\app\-WEBSPHERE1-HTML_WAS1_DV8093-AS_JS_DV8093-browser.log
[2017-05-19 12:52:33,093] INFO  - JdeBrowser - Adding to browser args : --webdriver-loglevel=INFO

The driver is created using:
driver = new PhantomJSDriver(caps)

After this it opens a few web pages and checks for some page elements.

The final steps are

driver?.close()
driver?.quit()

When the initial failure occurs the cleanup is to close and quit the driver before the script completes.  Each time this script runs the process starts from scratch.  I don’t know what would be left open that causes all the subsequent runs to fail to create a new instance of the driver.  Do you have any thoughts?  I should mention this is all done in a groovy script instantiated by the logic monitor scheduling tool  for each individual run.


Regards,

Marc Fick | Sr. Developer
GSI, Inc. | ERP Expertise. Business IQ. Cloud Sense.
w: 877-474-4262 x762| c: 507-838-0673 | GetGSI.com<http://www.getgsi.com/>

[signature2]

**Comment by kensoh** [comment]
@fickmj I see you are saying even if something fails you have handling to close and quit the driver gracefully. Hmm can't think of anything that could cause it. As the error seems to happen at the interface between Selenium and GhostDriver need to investigate what breaks there.

Copying GhostDriver current maintainer @jesg as error in your post looks like a call to it. But know that as the parent project PhantomJS is stalled out, GhostDriver project probably has no point in making updates, and it may be better to raise an issue there linking to this issue for tracking.

```
The driver is created using:
driver = new PhantomJSDriver(caps)

After this it opens a few web pages and checks for some page elements.

The final steps are

driver?.close()
driver?.quit()

When the initial failure occurs the cleanup is to close and quit the driver before the script completes.  Each time this script runs the process starts from scratch.  I don’t know what would be left open that causes all the subsequent runs to fail to create a new instance of the driver.  Do you have any thoughts?  I should mention this is all done in a groovy script instantiated by the logic monitor scheduling tool  for each individual run.
```
