### ISSUE TITLE
Crash report on Azure build

### ISSUE THREAD

**Issue by 130nk3r5** [ariya/phantomjs#15160]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
2.1.1

2. What steps will reproduce the problem?
Build on Azure

3. Which operating system are you using?
Azure

4. Did you use binary PhantomJS or did you compile it from source?
au test command on Azure

5. Please provide any additional information below.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
[31m13 10 2017 08:09:56.769:ERROR [launcher]: [39mPhantomJS crashed.
	
[32m13 10 2017 08:09:56.776:INFO [launcher]: [39mTrying to start PhantomJS again (1/2).
[33m13 10 2017 08:10:08.549:WARN [PhantomJS 2.1.1 (Windows 8 0.0.0)]: [39mDisconnected (1 times), because no message in 10000 ms.
[31m13 10 2017 08:10:08.629:ERROR [karma]: [39mTypeError: Invalid date
    at TypeError (native)
    at d:\a\3\s\FrontEndApp\node_modules\dateformat\lib\dateformat.js:39:17
    at toISOString (d:\a\3\s\FrontEndApp\node_modules\karma-tfs-reporter\trx.js:14:12)
    at module.exports (d:\a\3\s\FrontEndApp\node_modules\karma-tfs-reporter\trx.js:119:24)
    at TfsReporter.onExit (d:\a\3\s\FrontEndApp\node_modules\karma-tfs-reporter\index.js:53:44)
    at Server.<anonymous> (d:\a\3\s\FrontEndApp\node_modules\karma\lib\events.js:13:22)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at Server.EventEmitter.emitAsync (d:\a\3\s\FrontEndApp\node_modules\karma\lib\events.js:72:10)
    at disconnectBrowsers (d:\a\3\s\FrontEndApp\node_modules\karma\lib\server.js:339:10)
    at Server.<anonymous> (d:\a\3\s\FrontEndApp\node_modules\karma\lib\server.js:294:7)
    at emitTwo (events.js:111:20)
    at Server.emit (events.js:191:7)
    at emitRunCompleteIfAllBrowsersDone (d:\a\3\s\FrontEndApp\node_modules\karma\lib\server.js:259:12)
    at Server.<anonymous> (d:\a\3\s\FrontEndApp\node_modules\karma\lib\server.js:281:9)
    at emitOne (events.js:101:20)
d:\a\3\s\FrontEndApp\node_modules\dateformat\lib\dateformat.js:39
          throw TypeError('Invalid date');
          ^
TypeError: Invalid date
    at TypeError (native)
    at d:\a\3\s\FrontEndApp\node_modules\dateformat\lib\dateformat.js:39:17
    at toISOString (d:\a\3\s\FrontEndApp\node_modules\karma-tfs-reporter\trx.js:14:12)
    at module.exports (d:\a\3\s\FrontEndApp\node_modules\karma-tfs-reporter\trx.js:119:24)
    at TfsReporter.onExit (d:\a\3\s\FrontEndApp\node_modules\karma-tfs-reporter\index.js:53:44)
    at Server.<anonymous> (d:\a\3\s\FrontEndApp\node_modules\karma\lib\events.js:13:22)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at Server.EventEmitter.emitAsync (d:\a\3\s\FrontEndApp\node_modules\karma\lib\events.js:72:10)
    at disconnectBrowsers (d:\a\3\s\FrontEndApp\node_modules\karma\lib\server.js:339:10)
    at process.<anonymous> (d:\a\3\s\FrontEndApp\node_modules\karma\lib\server.js:359:5)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:296:26)
Process completed with exit code 7.

**Comment by 130nk3r5** [comment]
Had to change the browserNoActivityTimeout to 60000 in karma.config.js
