### ISSUE TITLE
Global install on mac fails for prebuilt  version (dependency of vorlonjs)

### ISSUE THREAD

**Issue by weird-dreams** [ariya/phantomjs#15305]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
v2.1.1/phantomjs-2.1.1-macosx.zip

2. What steps will reproduce the problem?
  1. we wanted to install vorlonjs (sudo npm i -g vorlon)
  2. this fails due to an EACCES when installing a link
 ```
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1517823958480/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/phantom
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1517823958480/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/phantom'
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1517823958480/phantomjs-2.1.1-macosx',
  dest: '/usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1517823958480/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/phantom'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
```
3. Which operating system are you using?
mac os x el capitan (10.11.6)

4. Did you use binary PhantomJS or did you compile it from source?

5. Please provide any additional information below.
```
Considering PhantomJS found at /usr/local/bin/phantomjs

Looks like an `npm install -g`

Found PhantomJS at /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ...verifying

Writing location.js file

Error checking path, continuing { Error: EACCES: permission denied, open '/usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/location.js'

    at Object.fs.openSync (fs.js:646:18)

    at Object.fs.writeFileSync (fs.js:1291:33)

    at writeLocationFile (/usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/util.js:84:6)

    at Promise._successFn (/usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/install.js:366:11)

    at nextTickCallback (/usr/local/lib/node_modules/vorlon/node_modules/kew/kew.js:47:28)

    at _combinedTickCallback (internal/process/next_tick.js:131:7)

    at process._tickCallback (internal/process/next_tick.js:180:9)

  errno: -13,

  code: 'EACCES',

  syscall: 'open',

  path: '/usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/location.js' }

Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip

Saving to /tmp/phantomjs/phantomjs-2.1.1-macosx.zip

Receiving...

  [========================================] 99%

Received 16746K total.

Extracting zip contents

Removing /usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/phantom

Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1517823958480/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/phantom

Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1517823958480/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/phantom'

  errno: -13,

  code: 'EACCES',

  syscall: 'link',

  path: '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1517823958480/phantomjs-2.1.1-macosx',

  dest: '/usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1517823958480/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/vorlon/node_modules/phantomjs-prebuilt/lib/phantom'

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:

npm ERR!     




```

**Comment by pixiuPL** [comment]
@weird-dreams Please see [this](http://phantomjs.org/anon)
Please migrate to newest version (2.1.3)
